### ISSUE TITLE
Make mus_ws_unittests (services_unittests now) pass

### ISSUE THREAD

**Issue by fred-wang** [Igalia/chromium#11]
Currently the mus ws unit tests (services_unittests now) pass on ozone-wayland-dev but they do not on ozone-wayland-chrome.

One of the issue is that these tests require the window manager access policy. There are more crashes / hangs that we need to analyze.

**Comment by fred-wang** [comment]
So applying https://github.com/Igalia/chromium/pull/20 and using the window manager policy, the only remaining failure is a crash in WindowTreeClientTest.SetWindowBounds ; it may be related to issue #14

**Comment by fred-wang** [comment]
New update: Applying https://github.com/Igalia/chromium/pull/32 and using the window manager policy, WindowTreeClientTest.SetWindowBounds no longer crashes and all the other tests pass. However, it still fails because of some change to DefaultAccessPolicy::CanSetWindowBounds that was done in 7ded6b39e32859aa10fd092f50403802443f32ae

@tonikitoo Can you explain what was the rationale for doing that change?

**Comment by fred-wang** [comment]
> @tonikitoo Can you explain what was the rationale for doing that change?

OK, it is needed to set initial bound of chrome (although resize still works).

**Comment by tonikitoo** [comment]
Precisely correct.

**Comment by fred-wang** [comment]
So all the tests now pass if we revert the policy change:
https://github.com/Igalia/chromium/commit/0455566f661763c4e85951338a2d5098390bed8d

However doing so breaks chrome. Not yet sure about how to address that.

**Comment by fred-wang** [comment]
Test has been disabled in our bot for now: https://build-chromium.igalia.com/#/builders/1/builds/145

**Comment by msisov** [comment]
fixed by: https://github.com/Igalia/chromium/pull/121 (workaround)

going to be completely fixed by: https://github.com/Igalia/chromium/pull/133

**Comment by tonikitoo** [comment]
Closing as fixed. Tests all pass since PR #121. Particularly, PR #149 has consolidated our access policy implementation.
