### ISSUE TITLE
ui::ws::Display::~Display are not deleted closing a window

### ISSUE THREAD

**Issue by tonikitoo** [Igalia/chromium#112]
open one browser window.
then open another (control+n or menu)
close a window pressing "x".

ui::ws::Display::~Display is never called.

**Comment by tonikitoo** [comment]
we are currently only destroying ui::ws::Display instances upon exit:

#0 0x556221d6b817 base::debug::StackTrace::StackTrace()
#1 0x556224db43c0 ui::ws::Display::~Display()
#2 0x556224db46a9 ui::ws::Display::~Display()
#3 0x556224d93d51 ui::ws::DisplayManager::DestroyDisplay()
#4 0x556224d93680 ui::ws::DisplayManager::DestroyAllDisplays()
#5 0x556224da0405 ui::ws::WindowServer::~WindowServer()
#6 0x556224da0839 ui::ws::WindowServer::~WindowServer()
#7 0x55622193ea18 ui::Service::~Service()
#8 0x55622193eba9 ui::Service::~Service()
(..)

**Comment by msisov** [comment]
Mostly a duplicate of https://github.com/Igalia/chromium/issues/66

**Comment by tonikitoo** [comment]
Ok, closing..
