### ISSUE TITLE
ozone/chromeos compilation is broken

### ISSUE THREAD

**Issue by tonikitoo** [Igalia/chromium#115]
$ time ninja -C out/ozone/chrome_os chrome mash:all ozone_unittests services/ui/demo/ services_unittests
ninja: Entering directory `out/ozone/chrome_os'
[707/1629] CXX obj/services/ui/display/tests/screen_manager_ozone_internal_unittests.o
FAILED: obj/services/ui/display/tests/screen_manager_ozone_internal_unittests.o 
../../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/services/ui/display/tests/screen_manager_ozone_internal_unittests.o.d -DV8_DEPRECATION_WARNINGS -DDCHECK_ALWAYS_ON=1 -DUSE_UDEV -DUSE_ASH=1 -DUSE_AURA=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DDISABLE_NACL -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -DCR_CLANG_REVISION=\"303910-1\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DOS_CHROMEOS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGL_GLEXT_PROTOTYPES -DUSE_GLX -DUSE_EGL -DANGLE_ENABLE_RELEASE_ASSERTS -DGTEST_API_= -DGTEST_HAS_POSIX_RE=0 -DGTEST_LANG_CXX11=1 -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DUCHAR_TYPE=uint16_t -DUNIT_TEST -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DSK_HAS_PNG_LIBRARY -DSK_HAS_WEBP_LIBRARY -DSK_HAS_JPEG_LIBRARY -DSK_SUPPORT_GPU=1 -DENABLE_IPC_FUZZER -DMESA_EGL_NO_X11_HEADERS -I../../.. -Igen -I../../../third_party/libwebp -I../../../third_party/khronos -I../../../gpu -I../../../third_party/googletest/src/googletest/include -I../../../third_party/ced/src -I../../../third_party/icu/source/common -I../../../third_party/icu/source/i18n -I../../../third_party/googletest/custom -I../../../third_party/googletest/src/googlemock/include -I../../../skia/config -I../../../skia/ext -I../../../third_party/skia/include/c -I../../../third_party/skia/include/config -I../../../third_party/skia/include/core -I../../../third_party/skia/include/effects -I../../../third_party/skia/include/encode -I../../../third_party/skia/include/images -I../../../third_party/skia/include/lazy -I../../../third_party/skia/include/pathops -I../../../third_party/skia/include/pdf -I../../../third_party/skia/include/pipe -I../../../third_party/skia/include/ports -I../../../third_party/skia/include/utils -I../../../third_party/skia/third_party/vulkan -I../../../third_party/skia/include/gpu -I../../../third_party/skia/src/gpu -I../../../third_party/skia/src/sksl -I../../../third_party/mesa/src/include -fno-strict-aliasing -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -B../../../third_party/binutils/Linux_x64/Release/bin -pthread -fcolor-diagnostics -m64 -march=x86-64 -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wno-shift-negative-value -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-address-of-packed-member -Wno-unused-lambda-capture -Wno-user-defined-warnings -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g1 --sysroot=../../../build/linux/debian_jessie_amd64-sysroot -fvisibility=hidden -Xclang -load -Xclang ../../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-auto-raw-pointer -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -std=gnu++11 -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -c ../../../services/ui/display/screen_manager_ozone_internal_unittests.cc -o obj/services/ui/display/tests/screen_manager_ozone_internal_unittests.o
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:192:29: error: field type 'display::(anonymous namespace)::TestScreenManagerDelegate' is an abstract class
  TestScreenManagerDelegate delegate_;
                            ^
../../../services/ui/display/screen_manager_delegate.h:37:16: note: unimplemented pure virtual method 'OnHostDisplaysReady' in 'TestScreenManagerDelegate'
  virtual void OnHostDisplaysReady(const ui::ws::UserId& user_id) = 0;
               ^
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:137:5: error: cannot initialize object parameter of type 'ui::TaskRunnerTestBase' with an expression of type 'display::ScreenManagerOzoneInternalTest'
    RunAllTasks();
    ^~~~~~~~~~~
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:143:5: error: cannot initialize object parameter of type 'ui::TaskRunnerTestBase' with an expression of type 'display::ScreenManagerOzoneInternalTest'
    RunAllTasks();
    ^~~~~~~~~~~
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:153:25: error: cannot initialize object parameter of type 'ui::TaskRunnerTestBase' with an expression of type 'display::ScreenManagerOzoneInternalTest'
    TaskRunnerTestBase::SetUp();
                        ^~~~~
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:175:5: error: cannot initialize object parameter of type 'ui::TaskRunnerTestBase' with an expression of type 'display::ScreenManagerOzoneInternalTest'
    RunAllTasks();
    ^~~~~~~~~~~
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:197:3: error: no matching member function for call to 'AddDisplay'
  AddDisplay(FakeDisplaySnapshot::Builder()
  ^~~~~~~~~~
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:135:8: note: candidate function not viable: no known conversion from 'display::ScreenManagerOzoneInternalTest_AddDisplay_Test' to 'display::ScreenManagerOzoneInternalTest' for object argument
  void AddDisplay(std::unique_ptr<DisplaySnapshot> snapshot) {
       ^
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:128:8: note: candidate function not viable: no known conversion from 'display::ScreenManagerOzoneInternalTest_AddDisplay_Test' to 'display::ScreenManagerOzoneInternalTest' for object argument
  void AddDisplay(int64_t id) {
       ^
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:203:25: error: cannot initialize object parameter of type 'display::ScreenManagerOzoneInternalTest' with an expression of type 'display::ScreenManagerOzoneInternalTest_AddDisplay_Test'
  EXPECT_EQ("Added(2)", delegate()->changes());
                        ^~~~~~~~
../../../third_party/googletest/src/googletest/include/gtest/gtest.h:1925:29: note: expanded from macro 'EXPECT_EQ'
                      val1, val2)
                            ^~~~
../../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:162:40: note: expanded from macro 'EXPECT_PRED_FORMAT2'
  GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
                                       ^~
../../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:147:43: note: expanded from macro 'GTEST_PRED_FORMAT2_'
  GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), \
                                          ^~
../../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:77:52: note: expanded from macro 'GTEST_ASSERT_'
  if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                   ^~~~~~~~~~
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:204:15: error: cannot initialize object parameter of type 'display::ScreenManagerOzoneInternalTest' with an expression of type 'display::ScreenManagerOzoneInternalTest_AddDisplay_Test'
  EXPECT_THAT(delegate()->added()[0], DisplayPixelSizeIs("1600x900"));
              ^~~~~~~~
../../../third_party/googletest/src/googlemock/include/gmock/gmock-matchers.h:4389:70: note: expanded from macro 'EXPECT_THAT'
    ::testing::internal::MakePredicateFormatterFromMatcher(matcher), value)
                                                                     ^~~~~
../../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:114:36: note: expanded from macro 'EXPECT_PRED_FORMAT1'
  GTEST_PRED_FORMAT1_(pred_format, v1, GTEST_NONFATAL_FAILURE_)
                                   ^~
../../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:101:34: note: expanded from macro 'GTEST_PRED_FORMAT1_'
  GTEST_ASSERT_(pred_format(#v1, v1), \
                                 ^~
../../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:77:52: note: expanded from macro 'GTEST_ASSERT_'
  if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                   ^~~~~~~~~~
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:205:15: error: cannot initialize object parameter of type 'display::ScreenManagerOzoneInternalTest' with an expression of type 'display::ScreenManagerOzoneInternalTest_AddDisplay_Test'
  EXPECT_THAT(delegate()->added()[0], DisplayBoundsIs("1024,0 1600x900"));
              ^~~~~~~~
../../../third_party/googletest/src/googlemock/include/gmock/gmock-matchers.h:4389:70: note: expanded from macro 'EXPECT_THAT'
    ::testing::internal::MakePredicateFormatterFromMatcher(matcher), value)
                                                                     ^~~~~
../../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:114:36: note: expanded from macro 'EXPECT_PRED_FORMAT1'
  GTEST_PRED_FORMAT1_(pred_format, v1, GTEST_NONFATAL_FAILURE_)
                                   ^~
../../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:101:34: note: expanded from macro 'GTEST_PRED_FORMAT1_'
  GTEST_ASSERT_(pred_format(#v1, v1), \
                                 ^~
../../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:77:52: note: expanded from macro 'GTEST_ASSERT_'
  if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                   ^~~~~~~~~~
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:209:3: error: no matching member function for call to 'AddDisplay'
  AddDisplay(2);
  ^~~~~~~~~~
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:128:8: note: candidate function not viable: no known conversion from 'display::ScreenManagerOzoneInternalTest_RemoveDisplay_Test' to 'display::ScreenManagerOzoneInternalTest' for object argument
  void AddDisplay(int64_t id) {
       ^
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:135:8: note: candidate function not viable: no known conversion from 'display::ScreenManagerOzoneInternalTest_RemoveDisplay_Test' to 'display::ScreenManagerOzoneInternalTest' for object argument
  void AddDisplay(std::unique_ptr<DisplaySnapshot> snapshot) {
       ^
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:210:3: error: cannot initialize object parameter of type 'display::ScreenManagerOzoneInternalTest' with an expression of type 'display::ScreenManagerOzoneInternalTest_RemoveDisplay_Test'
  delegate()->Reset();
  ^~~~~~~~
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:212:3: error: cannot initialize object parameter of type 'display::ScreenManagerOzoneInternalTest' with an expression of type 'display::ScreenManagerOzoneInternalTest_RemoveDisplay_Test'
  RemoveDisplay(2);
  ^~~~~~~~~~~~~
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:215:27: error: cannot initialize object parameter of type 'display::ScreenManagerOzoneInternalTest' with an expression of type 'display::ScreenManagerOzoneInternalTest_RemoveDisplay_Test'
  EXPECT_EQ("Removed(2)", delegate()->changes());
                          ^~~~~~~~
../../../third_party/googletest/src/googletest/include/gtest/gtest.h:1925:29: note: expanded from macro 'EXPECT_EQ'
                      val1, val2)
                            ^~~~
../../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:162:40: note: expanded from macro 'EXPECT_PRED_FORMAT2'
  GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
                                       ^~
../../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:147:43: note: expanded from macro 'GTEST_PRED_FORMAT2_'
  GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), \
                                          ^~
../../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:77:52: note: expanded from macro 'GTEST_ASSERT_'
  if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                   ^~~~~~~~~~
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:219:3: error: no matching member function for call to 'AddDisplay'
  AddDisplay(2);
  ^~~~~~~~~~
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:128:8: note: candidate function not viable: no known conversion from 'display::ScreenManagerOzoneInternalTest_DISABLED_RemovePrimaryDisplay_Test' to 'display::ScreenManagerOzoneInternalTest' for object argument
  void AddDisplay(int64_t id) {
       ^
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:135:8: note: candidate function not viable: no known conversion from 'display::ScreenManagerOzoneInternalTest_DISABLED_RemovePrimaryDisplay_Test' to 'display::ScreenManagerOzoneInternalTest' for object argument
  void AddDisplay(std::unique_ptr<DisplaySnapshot> snapshot) {
       ^
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:220:3: error: cannot initialize object parameter of type 'display::ScreenManagerOzoneInternalTest' with an expression of type 'display::ScreenManagerOzoneInternalTest_DISABLED_RemovePrimaryDisplay_Test'
  delegate()->Reset();
  ^~~~~~~~
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:222:3: error: cannot initialize object parameter of type 'display::ScreenManagerOzoneInternalTest' with an expression of type 'display::ScreenManagerOzoneInternalTest_DISABLED_RemovePrimaryDisplay_Test'
  RemoveDisplay(1);
  ^~~~~~~~~~~~~
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:226:50: error: cannot initialize object parameter of type 'display::ScreenManagerOzoneInternalTest' with an expression of type 'display::ScreenManagerOzoneInternalTest_DISABLED_RemovePrimaryDisplay_Test'
  EXPECT_EQ("Removed(1);Modified(2);Primary(2)", delegate()->changes());
                                                 ^~~~~~~~
../../../third_party/googletest/src/googletest/include/gtest/gtest.h:1925:29: note: expanded from macro 'EXPECT_EQ'
                      val1, val2)
                            ^~~~
../../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:162:40: note: expanded from macro 'EXPECT_PRED_FORMAT2'
  GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
                                       ^~
../../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:147:43: note: expanded from macro 'GTEST_PRED_FORMAT2_'
  GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), \
                                          ^~
../../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:77:52: note: expanded from macro 'GTEST_ASSERT_'
  if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                   ^~~~~~~~~~
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:227:15: error: cannot initialize object parameter of type 'display::ScreenManagerOzoneInternalTest' with an expression of type 'display::ScreenManagerOzoneInternalTest_DISABLED_RemovePrimaryDisplay_Test'
  ASSERT_THAT(delegate()->modified(), SizeIs(1));
              ^~~~~~~~
../../../third_party/googletest/src/googlemock/include/gmock/gmock-matchers.h:4387:70: note: expanded from macro 'ASSERT_THAT'
    ::testing::internal::MakePredicateFormatterFromMatcher(matcher), value)
                                                                     ^~~~~
../../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:118:36: note: expanded from macro 'ASSERT_PRED_FORMAT1'
  GTEST_PRED_FORMAT1_(pred_format, v1, GTEST_FATAL_FAILURE_)
                                   ^~
../../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:101:34: note: expanded from macro 'GTEST_PRED_FORMAT1_'
  GTEST_ASSERT_(pred_format(#v1, v1), \
                                 ^~
../../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:77:52: note: expanded from macro 'GTEST_ASSERT_'
  if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                   ^~~~~~~~~~
../../../services/ui/display/screen_manager_ozone_internal_unittests.cc:228:15: error: cannot initialize object parameter of type 'display::ScreenManagerOzoneInternalTest' with an expression of type 'display::ScreenManagerOzoneInternalTest_DISABLED_RemovePrimaryDisplay_Test'
  EXPECT_THAT(delegate()->modified()[0], DisplayIdIs(2));
              ^~~~~~~~
../../../third_party/googletest/src/googlemock/include/gmock/gmock-matchers.h:4389:70: note: expanded from macro 'EXPECT_THAT'
    ::testing::internal::MakePredicateFormatterFromMatcher(matcher), value)
                                                                     ^~~~~
../../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:114:36: note: expanded from macro 'EXPECT_PRED_FORMAT1'
  GTEST_PRED_FORMAT1_(pred_format, v1, GTEST_NONFATAL_FAILURE_)
                                   ^~
../../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:101:34: note: expanded from macro 'GTEST_PRED_FORMAT1_'
  GTEST_ASSERT_(pred_format(#v1, v1), \
                                 ^~
../../../third_party/googletest/src/googletest/include/gtest/gtest_pred_impl.h:77:52: note: expanded from macro 'GTEST_ASSERT_'
  if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                   ^~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
[748/1629] CXX obj/headless/headless/headless_browser_impl.o
ninja: build stopped: subcommand failed.

**Comment by tonikitoo** [comment]
the broken target is 'services_unittests'

**Comment by msisov** [comment]
fixed by https://github.com/Igalia/chromium/pull/119
