### ISSUE TITLE
linux/x11 compilation is broken

### ISSUE THREAD

**Issue by tonikitoo** [Igalia/chromium#118]
$ time ninja -C out/x11  chrome 
ninja: Entering directory `out/x11'
[1/1] Regenerating ninja files
[1288/1634] CXX obj/ui/views/views/desktop_window_tree_host_x11.o
FAILED: obj/ui/views/views/desktop_window_tree_host_x11.o 
../../home/tonikitoo/Devel/chromium/src/third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/ui/views/views/desktop_window_tree_host_x11.o.d -DVIEWS_IMPLEMENTATION -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DDISABLE_NACL -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -DCR_CLANG_REVISION=\"303910-1\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DCOMPONENT_BUILD -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DATK_LIB_DIR=\"/usr/lib/x86_64-linux-gnu\" -DTOOLKIT_VIEWS=1 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_32 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_26 -DGL_GLEXT_PROTOTYPES -DUSE_GLX -DUSE_EGL -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DSK_HAS_PNG_LIBRARY -DSK_HAS_WEBP_LIBRARY -DSK_HAS_JPEG_LIBRARY -DSKIA_DLL -DGR_GL_IGNORE_ES3_MSAA=0 -DSK_SUPPORT_GPU=1 -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DUCHAR_TYPE=uint16_t -I../../home/tonikitoo/Devel/chromium/src -Igen -I../../home/tonikitoo/Devel/chromium/src/build/linux/debian_jessie_amd64-sysroot/usr/include/atk-1.0 -I../../home/tonikitoo/Devel/chromium/src/build/linux/debian_jessie_amd64-sysroot/usr/include/glib-2.0 -I../../home/tonikitoo/Devel/chromium/src/build/linux/debian_jessie_amd64-sysroot/usr/lib/x86_64-linux-gnu/glib-2.0/include -I../../home/tonikitoo/Devel/chromium/src/build/linux/debian_jessie_amd64-sysroot/usr/include/glib-2.0 -I../../home/tonikitoo/Devel/chromium/src/build/linux/debian_jessie_amd64-sysroot/usr/lib/x86_64-linux-gnu/glib-2.0/include -I../../home/tonikitoo/Devel/chromium/src/third_party/libwebp -I../../home/tonikitoo/Devel/chromium/src/third_party/khronos -I../../home/tonikitoo/Devel/chromium/src/gpu -Igen -I../../home/tonikitoo/Devel/chromium/src/skia/config -I../../home/tonikitoo/Devel/chromium/src/skia/ext -I../../home/tonikitoo/Devel/chromium/src/third_party/skia/include/c -I../../home/tonikitoo/Devel/chromium/src/third_party/skia/include/config -I../../home/tonikitoo/Devel/chromium/src/third_party/skia/include/core -I../../home/tonikitoo/Devel/chromium/src/third_party/skia/include/effects -I../../home/tonikitoo/Devel/chromium/src/third_party/skia/include/encode -I../../home/tonikitoo/Devel/chromium/src/third_party/skia/include/images -I../../home/tonikitoo/Devel/chromium/src/third_party/skia/include/lazy -I../../home/tonikitoo/Devel/chromium/src/third_party/skia/include/pathops -I../../home/tonikitoo/Devel/chromium/src/third_party/skia/include/pdf -I../../home/tonikitoo/Devel/chromium/src/third_party/skia/include/pipe -I../../home/tonikitoo/Devel/chromium/src/third_party/skia/include/ports -I../../home/tonikitoo/Devel/chromium/src/third_party/skia/include/utils -I../../home/tonikitoo/Devel/chromium/src/third_party/skia/third_party/vulkan -I../../home/tonikitoo/Devel/chromium/src/third_party/skia/include/gpu -I../../home/tonikitoo/Devel/chromium/src/third_party/skia/src/gpu -I../../home/tonikitoo/Devel/chromium/src/third_party/skia/src/sksl -I../../home/tonikitoo/Devel/chromium/src/third_party/icu/source/common -I../../home/tonikitoo/Devel/chromium/src/third_party/icu/source/i18n -I../../home/tonikitoo/Devel/chromium/src/third_party/ced/src -I../../home/tonikitoo/Devel/chromium/src/third_party/mesa/src/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -B../../home/tonikitoo/Devel/chromium/src/third_party/binutils/Linux_x64/Release/bin -pthread -fcolor-diagnostics -m64 -march=x86-64 -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-address-of-packed-member -Wno-unused-lambda-capture -Wno-user-defined-warnings -O2 -fno-ident -fdata-sections -ffunction-sections -fomit-frame-pointer -g0 --sysroot=../../home/tonikitoo/Devel/chromium/src/build/linux/debian_jessie_amd64-sysroot -fvisibility=hidden -Xclang -load -Xclang ../../home/tonikitoo/Devel/chromium/src/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-auto-raw-pointer -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wno-unused-local-typedef -Wno-unused-function -std=gnu++11 -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -c ../../home/tonikitoo/Devel/chromium/src/ui/views/widget/desktop_aura/desktop_window_tree_host_x11.cc -o obj/ui/views/views/desktop_window_tree_host_x11.o
../../home/tonikitoo/Devel/chromium/src/ui/views/widget/desktop_aura/desktop_window_tree_host_x11.cc:2285:14: error: allocating an object of abstract class type 'views::DesktopWindowTreeHostX11'
  return new DesktopWindowTreeHostX11(native_widget_delegate,
             ^
../../home/tonikitoo/Devel/chromium/src/ui/views/widget/desktop_aura/desktop_window_tree_host.h:176:16: note: unimplemented pure virtual method 'PerformNativeWindowDragOrResize' in 'DesktopWindowTreeHostX11'
  virtual void PerformNativeWindowDragOrResize(int hittest) = 0;
               ^
1 error generated.
[1304/1634] CXX obj/ui/views/controls/webview/webview/web_dialog_view.o
ninja: build stopped: subcommand failed.

real	3m50.078s
user	137m32.592s
sys	6m59.400s

**Comment by msisov** [comment]
Hm, I don't get this error. And that method is implemented, actually. See this - https://github.com/Igalia/chromium/commit/d77978dcaef2d2c4d6c5cbe7412a3e843f8a01da#diff-718e876b3b97a30f09d59f6f00479502R1136

**Comment by msisov** [comment]
closing, no actions needed
