### ISSUE TITLE
Rename Display::OnWillDestroyTree

### ISSUE THREAD

**Issue by fred-wang** [Igalia/chromium#12]
Display::OnWillDestroyTree is a bad name for external mode since the window tree is actually destroyed once all the "displays" == "external mode windows" attached to it are closed. It should probably be called Display::OnWillBeDetachedFromTree or similar.

**Comment by msisov** [comment]
tonikitoo, do you think this name is ok to have or should we call it something like OnWindowTreeWillBeDestroyed or RemoveWindowTreeFromMap?
