### ISSUE TITLE
Assert hit: open menus + windows with mouse multiple times

### ISSUE THREAD

**Issue by tonikitoo** [Igalia/chromium#125]
[33499:33499:0623/150456.327674:FATAL:window_event_dispatcher.cc(204)] Check failed: move_hold_count_ >= 0 (-1 vs. 0)
#0 0x5640dccda3a7 base::debug::StackTrace::StackTrace()
#1 0x5640dccf433d logging::LogMessage::~LogMessage()
#2 0x5640ddf49901 aura::WindowEventDispatcher::ReleasePointerMoves()
#3 0x5640ddf41ba5 aura::WindowTreeClient::OnCompositingEnded()
#4 0x5640ddf597f4 ui::Compositor::DidReceiveCompositorFrameAck()
#5 0x5640db00e567 _ZN4base8internal7InvokerINS0_9BindStateIMN7content21EmbeddedServiceRunnerEFvvEJNS_7WeakPtrIS4_EEEEEFvvEE3RunEPNS0_13BindStateBaseE
#6 0x5640daf79381 _ZNO4base8CallbackIFvvELNS_8internal8CopyModeE1ELNS2_10RepeatModeE1EE3RunEv
#7 0x5640dcd88623 base::debug::TaskAnnotator::RunTask()
#8 0x5640dccfb7dd base::MessageLoop::RunTask()
#9 0x5640dccfbab8 base::MessageLoop::DeferOrRunPendingTask()
#10 0x5640dccfbea7 base::MessageLoop::DoWork()
#11 0x5640dccfe5a9 base::MessagePumpLibevent::Run()
#12 0x5640dccfb3b2 base::MessageLoop::Run()
#13 0x5640dcd246e7 base::RunLoop::Run()
#14 0x5640dcb983ff ChromeBrowserMainParts::MainMessageLoopRun()
#15 0x5640db560a62 content::BrowserMainLoop::RunMainMessageLoopParts()
#16 0x5640db5636d7 content::BrowserMainRunnerImpl::Run()
#17 0x5640db55c198 content::BrowserMain()
#18 0x5640dc8b6bbf content::RunNamedProcessTypeMain()
#19 0x5640dc8b7562 content::ContentMainRunnerImpl::Run()
#20 0x5640dc8d501f service_manager::Main()
#21 0x5640dc8b62f2 content::ContentMain()
#22 0x5640daef717d ChromeMain
#23 0x7fb2426b33f1 __libc_start_main
#24 0x5640daef6fbd <unknown>

**Comment by tonikitoo** [comment]
started. I face it all the time.

**Comment by msisov** [comment]
The commit is no longer needed after https://chromium-review.googlesource.com/c/chromium/src/+/713575 . I checked multiple clicking and never faced any problems.

**Comment by tonikitoo** [comment]
Yes, I agree it is not needed anymore.

The problem was that it was assumed a 1:1 relationship between WindowTreeClient and WindowTreeHost.

Now it is fixed, the relationship is 1:n.
