### ISSUE TITLE
neo keyboard layout not working

### ISSUE THREAD

**Issue by rroohhh** [Igalia/chromium#126]
Using the german neo variant I get totally wrong keys, i.e QWERTY "u" gets me "7" as opposed to "h".

**Comment by msisov** [comment]
I was told that Japanese layout has some problems as well. For example, it is not possible to enter certain symbols, which require "shift" key to be pressed and hold. For example, "shift" key + a certain key (depends on the layout), which produces ":" symbol.

**Comment by msisov** [comment]
the issue moved to the upstream - https://bugs.chromium.org/p/chromium/issues/detail?id=921947
