### ISSUE TITLE
Support xdg shell v6

### ISSUE THREAD

**Issue by msisov** [Igalia/chromium#137]
That's it. Add support for xdg shell v6 in wayland implemention.

**Comment by msisov** [comment]
started

**Comment by tonikitoo** [comment]
the preliminary first step has landed in ozone-wayland-dev branch, by @msisov. See PR #144.

**Comment by msisov** [comment]
closing this. Will open new issue if regressions found. At the moment, there is only one regression - https://github.com/Igalia/chromium/issues/147
