### ISSUE TITLE
Regression(xdg_v6): context menu do not show up immediately

### ISSUE THREAD

**Issue by tonikitoo** [Igalia/chromium#147]
Bisecting has revealed that the xdg_v6 (PR #144) support patch has regressed one use case: context menus do not seem to show up immediately after left clicking. Instead, it requires a slightly mouse move (locally) to finally render.

**Comment by msisov** [comment]
assigning to myself

**Comment by msisov** [comment]
working on it

**Comment by msisov** [comment]
Only reproducible in Weston. No issues are found with Gnome on Wayland

**Comment by msisov** [comment]
Lowering the priority of this issue. It's hard to track the roots of that. All the possible blocks from chromium side are checked (wl_display_dispatch, wl_display_flush, eglBuffersSwap and etc). Seems like a problem with mesa drivers???? From wayland debug I can see that wl_drm buffer is created and wl_surface is committed, but then nothing happens. And as soon as I move the mouse, server sends pong request and the popup is rendered.

**Comment by msisov** [comment]
I doesn't seem to be reproducible on most of our environments. Closing it then
