### ISSUE TITLE
Fix warning when building with jessie sysroot/clang

### ISSUE THREAD

**Issue by tonikitoo** [Igalia/chromium#15]
(...)
1 warning generated.
[16353/27046] CXX obj/services/ui/ws/mus_ws_unittests/window_tree_unittest.o
In file included from ../../../home/tonikitoo/Devel/chromium/src/services/ui/ws/window_tree_unittest.cc:5:
../../../home/tonikitoo/Devel/chromium/src/services/ui/ws/window_tree.h:623:36: warning: [chromium-style] WeakPtrFactory members which refer to their outer class must be the last member in the outer class definition.
  base::WeakPtrFactory<WindowTree> drag_weak_factory_;
                                   ^
1 warning generated.
[27046/27046] LINK ./chrome

**Comment by fred-wang** [comment]
Fixed by https://github.com/Igalia/chromium/pull/25
