### ISSUE TITLE
Finish implementation of InputMethod service in non-ChromeOS

### ISSUE THREAD

**Issue by tonikitoo** [Igalia/chromium#155]
We have PR #45, where inputting via keyboard was made minimally functionally, and PR #154, where we switched to "classic IME" in order to have a more complete input method implementation.

This bug tracks finishing the implementation of InputMethod service for non-ChromeOS.

**Comment by msisov** [comment]
#312

**Comment by msisov** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=791920&desc=3

we have a completely functional IME now. Thanks @zhani
