### ISSUE TITLE
mouse cursor offsets its position when changing type

### ISSUE THREAD

**Issue by tonikitoo** [Igalia/chromium#166]
hover the mouse cursor around some content with regular text and links. it is visible to see that the mouse position slightly changes while the mouse type changes.

**Comment by tonikitoo** [comment]
chromeos/mash also presents the same behavior. chromeos/mus does not. 

the mouse cursor path used in both configurations is different.

**Comment by tonikitoo** [comment]
checking this a little.

**Comment by msisov** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=869286
