### ISSUE TITLE
FATAL:latency_tracker.cc(196)] Check failed: gpu_swap_begin_component.last_event_time >= original_component.first_event_time (42321552294 bogo-microseconds vs. 3419125241000 bogo-microseconds)

### ISSUE THREAD

**Issue by msisov** [Igalia/chromium#179]
The issue happens only with Wayland backend. 

How to reproduce:
1) Start chromium/wayland with a new profile (--user-data-dir=/tmp/empty-profile)
2) Load riot.igalia.com
3) Start typing anything to "username" field.
4) Observe the crash.

[23139:23139:0810/135831.606993:42321552530:FATAL:latency_tracker.cc(196)] Check failed: gpu_swap_begin_component.last_event_time >= original_component.first_event_time (42321552294 bogo-microseconds vs. 3419125241000 bogo-microseconds)
#0 0x7f1fd4fb173d base::debug::StackTrace::StackTrace()
#1 0x7f1fd4fafb0c base::debug::StackTrace::StackTrace()
#2 0x7f1fd504022a logging::LogMessage::~LogMessage()
#3 0x7f1fbf082eae ui::LatencyTracker::ComputeEndToEndLatencyHistograms()
#4 0x7f1fbf081929 ui::LatencyTracker::OnGpuSwapBuffersCompleted()
#5 0x7f1fbef6a02d viz::DisplayOutputSurface::OnGpuSwapBuffersCompleted()
#6 0x7f1fbef6afb4 _ZN4base8internal13FunctorTraitsIMN3viz20DisplayOutputSurfaceEFvRKNSt3__16vectorIN2ui11LatencyInfoENS4_9allocatorIS7_EEEEN3gfx10SwapResultEPKN3gpu36GpuProcessHostedCALayerTreeParamsMacEEvE6InvokeIRKNS_7WeakPtrIS3_EEJSC_SE_SI_EEEvSK_OT_DpOT0_
#7 0x7f1fbef6aef5 _ZN4base8internal12InvokeHelperILb1EvE8MakeItSoIRKMN3viz20DisplayOutputSurfaceEFvRKNSt3__16vectorIN2ui11LatencyInfoENS6_9allocatorIS9_EEEEN3gfx10SwapResultEPKN3gpu36GpuProcessHostedCALayerTreeParamsMacEERKNS_7WeakPtrIS5_EEJSE_SG_SK_EEEvOT_OT0_DpOT1_
#8 0x7f1fbef6ae50 _ZN4base8internal7InvokerINS0_9BindStateIMN3viz20DisplayOutputSurfaceEFvRKNSt3__16vectorIN2ui11LatencyInfoENS5_9allocatorIS8_EEEEN3gfx10SwapResultEPKN3gpu36GpuProcessHostedCALayerTreeParamsMacEEJNS_7WeakPtrIS4_EEEEEFvSD_SF_SJ_EE7RunImplIRKSL_RKNS5_5tupleIJSN_EEEJLm0EEEEvOT_OT0_NS_13IndexSequenceIJXspT1_EEEESD_OSF_OSJ_
#9 0x7f1fbef6ad6f _ZN4base8internal7InvokerINS0_9BindStateIMN3viz20DisplayOutputSurfaceEFvRKNSt3__16vectorIN2ui11LatencyInfoENS5_9allocatorIS8_EEEEN3gfx10SwapResultEPKN3gpu36GpuProcessHostedCALayerTreeParamsMacEEJNS_7WeakPtrIS4_EEEEEFvSD_SF_SJ_EE3RunEPNS0_13BindStateBaseESD_OSF_OSJ_
#10 0x7f1fcc5c68f7 _ZNKR4base8CallbackIFvRKNSt3__16vectorIN2ui11LatencyInfoENS1_9allocatorIS4_EEEEN3gfx10SwapResultEPKN3gpu36GpuProcessHostedCALayerTreeParamsMacEELNS_8internal8CopyModeE1ELNSH_10RepeatModeE1EE3RunES9_SB_SF_
#11 0x7f1fcc5c4087 gpu::InProcessCommandBuffer::DidSwapBuffersCompleteOnOriginThread()
#12 0x7f1fcc5d31a1 _ZN4base8internal13FunctorTraitsIMN3gpu22InProcessCommandBufferEFvNS2_25SwapBuffersCompleteParamsEEvE6InvokeIRKNS_7WeakPtrIS3_EEJS4_EEEvS6_OT_DpOT0_
#13 0x7f1fcc5d30a5 _ZN4base8internal12InvokeHelperILb1EvE8MakeItSoIRKMN3gpu22InProcessCommandBufferEFvNS4_25SwapBuffersCompleteParamsEERKNS_7WeakPtrIS5_EEJS6_EEEvOT_OT0_DpOT1_
#14 0x7f1fcc5d2ff2 _ZN4base8internal7InvokerINS0_9BindStateIMN3gpu22InProcessCommandBufferEFvNS3_25SwapBuffersCompleteParamsEEJNS_7WeakPtrIS4_EENS0_13PassedWrapperIS5_EEEEEFvvEE7RunImplIRKS7_RKNSt3__15tupleIJS9_SB_EEEJLm0ELm1EEEEvOT_OT0_NS_13IndexSequenceIJXspT1_EEEE
#15 0x7f1fcc5d2edc _ZN4base8internal7InvokerINS0_9BindStateIMN3gpu22InProcessCommandBufferEFvNS3_25SwapBuffersCompleteParamsEEJNS_7WeakPtrIS4_EENS0_13PassedWrapperIS5_EEEEEFvvEE3RunEPNS0_13BindStateBaseE
#16 0x7f1fd4f5cde1 _ZNO4base8CallbackIFvvELNS_8internal8CopyModeE0ELNS2_10RepeatModeE0EE3RunEv
#17 0x7f1fd4fb6387 base::debug::TaskAnnotator::RunTask()
#18 0x7f1fd506f033 base::MessageLoop::RunTask()
#19 0x7f1fd506f2b7 base::MessageLoop::DeferOrRunPendingTask()
#20 0x7f1fd507003a base::MessageLoop::DoWork()
#21 0x7f1fd5078929 base::MessagePumpLibevent::Run()
#22 0x7f1fd506e744 base::MessageLoop::Run()
#23 0x7f1fd51235bd base::RunLoop::Run()
#24 0x7f1fd58bf93f service_manager::(anonymous namespace)::RunService()::$_0::operator()()
#25 0x7f1fd58bf186 _ZN4base8internal13FunctorTraitsIZN15service_manager12_GLOBAL__N_110RunServiceEPNS2_12MainDelegateEE3$_0vE6InvokeIJRKS5_RKPiN4mojo16InterfaceRequestINS2_5mojom7ServiceEEEEEEvRKS6_DpOT_
#26 0x7f1fd58bf0fd _ZN4base8internal12InvokeHelperILb0EvE8MakeItSoIRKZN15service_manager12_GLOBAL__N_110RunServiceEPNS4_12MainDelegateEE3$_0JRKS7_RKPiN4mojo16InterfaceRequestINS4_5mojom7ServiceEEEEEEvOT_DpOT0_
#27 0x7f1fd58bf09d _ZN4base8internal7InvokerINS0_9BindStateIZN15service_manager12_GLOBAL__N_110RunServiceEPNS3_12MainDelegateEE3$_0JS6_PiEEEFvN4mojo16InterfaceRequestINS3_5mojom7ServiceEEEEE7RunImplIRKS7_RKNSt3__15tupleIJS6_S8_EEEJLm0ELm1EEEEvOT_OT0_NS_13IndexSequenceIJXspT1_EEEEOSE_
#28 0x7f1fd58befa4 _ZN4base8internal7InvokerINS0_9BindStateIZN15service_manager12_GLOBAL__N_110RunServiceEPNS3_12MainDelegateEE3$_0JS6_PiEEEFvN4mojo16InterfaceRequestINS3_5mojom7ServiceEEEEE3RunEPNS0_13BindStateBaseEOSE_
#29 0x7f1fd58cbd50 _ZNKR4base8CallbackIFvN4mojo16InterfaceRequestIN15service_manager5mojom7ServiceEEEELNS_8internal8CopyModeE1ELNS8_10RepeatModeE1EE3RunES6_
#30 0x7f1fd58cb527 service_manager::RunStandaloneService()
#31 0x7f1fd58be3c8 service_manager::(anonymous namespace)::RunService()
#32 0x7f1fd58bd4d8 service_manager::Main()
#33 0x7f1fd04981cf content::ContentMain()

**Comment by msisov** [comment]
Doesn't seem to be reproducible after the latest rebasing.

**Comment by tonikitoo** [comment]
for me it seems reproducible on weston only (ubuntu 17.04) upon any mouse wheel event.
