### ISSUE TITLE
[ozone/wayland] control+click to open links in new tab does not work

### ISSUE THREAD

**Issue by tonikitoo** [Igalia/chromium#193]
SSIA

**Comment by ganguin** [comment]
same for me.

Actually for me, Shift, Ctrl, and alt do not work at all, for example:
# ctrl+t or +n +w +q do not work
# shift+anything does not capitaliye

Is it the same issue_

**Comment by msisov** [comment]
taking this issue

**Comment by msisov** [comment]
Ok, keyboard modifiers have not been applied in case of wayland.

**Comment by msisov** [comment]
#274 fixed.

The patch is being upstreamed at the moment

**Comment by msisov** [comment]
https://chromium-review.googlesource.com/c/chromium/src/+/718097/

**Comment by msisov** [comment]
The patch has been merged in the upstream. closing
