### ISSUE TITLE
Issue with touch events being dispatched to the wrong target

### ISSUE THREAD

**Issue by andrunko** [Igalia/chromium#214]
As discussed on IRC, opening this issue here to discuss an issue we are seeing in a not so old fork of the ozone-wayland-dev branch that is causing a crash when a touch sequence is dispatched to the wrong target window.

In summary, the issue happens when chromium receives 2 touch sequences for different surfaces, with each sequence being handled by a different WindowManagerState object, but then both WindowManagerState objects try to dispatch the sequences to the same WindowTree, which ends up confusing the GestureRecognizer that returns the wrong target window for the last sequence. 
This only happens if the last touch sequence arrives while the WindowManagerState object for the first sequence/surface still have the end-of-sequence events (up|cancel) in the queue to be processed and the other WindowManagerState object starts processing the new sequence, so the WindowTree ends up with a queue of events like down,move,move (previous sequence) + down (new sequence).

The main question here is, whether this use case above should be considered valid (it is reproducible in our version) and if so the fixes below should be on the right track, otherwise the fix needs to be somewhere in WindowManager to not mix touch event sequences when dispatching the events to WindowTree|Client.

The patch [attached](https://github.com/Igalia/chromium/files/1250769/touch-event-dispatch-wrong-target.txt) is on top of our version (attaching for reference for discussion). If we agree this is the correct fix I will rebase it on top of latest upstream.

The changes are basically:
1. use a unique (sequential) id for touch events received by WaylandTouch (id generated in WaylandTouch::Down) - to make sure we don't mess with the GestureRecognizer cache of (touch sequence id <-> target window) - see comment in code for more details
2. check if the target found by WindowTargeter::FindTargetInRootWindow is a descendent of root_window and if not return a null target (then the callers - more specifically WindowEventDispatcher::GetRootForEvent called from EventProcessor::OnEventFromSource - will search the target based on event->target ancestors and what not)

Note that this check for descendent was already done in WindowTargeter::FindTargetForEvent but not in WindowTargeter::FindTargetInRootWindow, with the exeption that WindowTargeter::FindTargetForEvent would also fwd the event to the correct target, while FindTargetInRootWindow only searches for it.

**Comment by tonikitoo** [comment]
possible related upstream CL: https://chromium-review.googlesource.com/c/chromium/src/+/634638

**Comment by msisov** [comment]
outdated. closed. reopen if anything in the crbug.com and add msisov@igalia.com to cc.
