### ISSUE TITLE
Notifications fail: ERROR:in_flight_change.cc(103)] change failed, type=11

### ISSUE THREAD

**Issue by msisov** [Igalia/chromium#215]
Notifications fail both in x11 and wayland.

how to reproduce:
1) open riot and enable notifications
2) ask someone to write something or write to our bot a private message, which it can answer
3) switch to another tab and then to another window.
4) once notification comes, chromium crashes

[33683:33683:0828/220821.857606:ERROR:in_flight_change.cc(103)] change failed, type=11
[33683:33683:0828/220821.857714:FATAL:in_flight_change.cc(104)] Check failed: false. 
#0 0x7f5b774aeb8d base::debug::StackTrace::StackTrace()
#1 0x7f5b774acf5c base::debug::StackTrace::StackTrace()
#2 0x7f5b7753d4ba logging::LogMessage::~LogMessage()
#3 0x7f5b6d069d2f aura::CrashInFlightChange::ChangeFailed()
#4 0x7f5b6d0bb2a2 aura::WindowTreeClient::OnChangeCompleted()
#5 0x7f5b6d1aab9d ui::mojom::WindowTreeClientStubDispatch::Accept()
#6 0x7f5b6d0cfed3 ui::mojom::WindowTreeClientStub<>::Accept()
#7 0x7f5b75b1557b mojo::InterfaceEndpointClient::HandleValidatedMessage()
#8 0x7f5b75b14071 mojo::InterfaceEndpointClient::HandleIncomingMessageThunk::Accept()
#9 0x7f5b75b123ac mojo::FilterChain::Accept()
#10 0x7f5b75b180e1 mojo::InterfaceEndpointClient::HandleIncomingMessage()
#11 0x7f5b75b305c7 mojo::internal::MultiplexRouter::ProcessIncomingMessage()
#12 0x7f5b75b2fadd mojo::internal::MultiplexRouter::Accept()
#13 0x7f5b75b123ac mojo::FilterChain::Accept()
#14 0x7f5b75b04f94 mojo::Connector::ReadSingleMessage()
#15 0x7f5b75b05ffa mojo::Connector::ReadAllAvailableMessages()
#16 0x7f5b75b05dbe mojo::Connector::OnHandleReadyInternal()
#17 0x7f5b75b05c9b mojo::Connector::OnWatcherHandleReady()

**Comment by tonikitoo** [comment]
I have not seen this in a while.

WORKSFORME
