### ISSUE TITLE
Crash happens when scrolling a webpage down using a touch pad

### ISSUE THREAD

**Issue by Gyuyoung** [Igalia/chromium#221]
After launching a Chrome on ozone-wayland-dev branch, I faced a crash when I scroll a webpage down.
If I have the crash because of wrong configuration or setting, please close this issue.

I've been using this configuration.

============================================
is_debug = false
is_component_build = false
symbol_level = 1 
dcheck_always_on = true

use_ozone = true
ozone_platform_wayland = true
ozone_platform_x11 = true
ozone_platform_gbm = false
ozone_platform_headless = false
ozone_auto_platforms = false

use_xkbcommon = true # this might be the missing bit!

use_ash = false
enable_package_mash_services = true

use_sysroot = true
treat_warnings_as_errors = false
is_clang = true

enable_nacl = false
remove_webcore_debug_symbols = true

use_jumbo_build = true

========================================

Below is a backtrace on the crash. 

========================================================================
gyuyoung@gyuyoung-XPS-15-9560:~/chromium/chromium-trunk/src$ ./out/Ozone/chrome 
--mus --ozone-platform=wayland
[7481:7514:0901/111711.080110:ERROR:xkb_keyboard_layout_engine.cc(694)] Not impl
emented reached in virtual bool ui::XkbKeyboardLayoutEngine::SetCurrentLayoutByN
ame(const std::string &)
[7481:7514:0901/111711.080947:ERROR:wayland_keyboard.cc(140)] Not implemented re
ached in static void ui::WaylandKeyboard::RepeatInfo(void *, wl_keyboard *, int3
2_t, int32_t)
[7481:7481:0901/111711.179269:ERROR:layer_tree_host_impl.cc(2404)] Forcing zero-
copy tile initialization as worker context is missing
[1:10:0901/111711.247651:ERROR:layer_tree_host_impl.cc(2404)] Forcing zero-copy 
tile initialization as worker context is missing
[1:10:0901/111712.869913:ERROR:layer_tree_host_impl.cc(2404)] Forcing zero-copy 
tile initialization as worker context is missing
[7481:7514:0901/111714.902781:ERROR:surface_aggregator.cc(208)] SurfaceId(FrameS
inkId(65546, 0), LocalSurfaceId(1, (652937F01439D410560ED07FF1D89725)lu)) is mis
sing during aggregation
[7481:7514:0901/111714.985948:ERROR:surface_aggregator.cc(208)] SurfaceId(FrameS
inkId(65546, 0), LocalSurfaceId(1, (652937F01439D410560ED07FF1D89725)lu)) is mis
sing during aggregation
[7481:7514:0901/111715.069076:ERROR:surface_aggregator.cc(208)] SurfaceId(FrameS
inkId(65546, 0), LocalSurfaceId(2, (D1A3B11484C399FDEE733BB7A9FC2A9F)lu)) is mis
sing during aggregation
[7481:7514:0901/111715.152794:ERROR:surface_aggregator.cc(208)] SurfaceId(FrameS
inkId(65546, 0), LocalSurfaceId(2, (D1A3B11484C399FDEE733BB7A9FC2A9F)lu)) is mis
sing during aggregation
[7481:7514:0901/111715.235443:ERROR:surface_aggregator.cc(208)] SurfaceId(FrameS
inkId(65546, 0), LocalSurfaceId(2, (D1A3B11484C399FDEE733BB7A9FC2A9F)lu)) is mis
sing during aggregation
[7481:7514:0901/111715.330357:ERROR:surface_aggregator.cc(208)] SurfaceId(FrameS
inkId(65546, 0), LocalSurfaceId(2, (D1A3B11484C399FDEE733BB7A9FC2A9F)lu)) is mis
sing during aggregation
[7481:7514:0901/111716.674931:FATAL:latency_tracker.cc(156)] Check failed: gpu_s
wap_begin_component.last_event_time >= original_component.first_event_time (6116
628444 bogo-microseconds vs. 993683057000 bogo-microseconds)
#0 0x55fb19a5abd7 base::debug::StackTrace::StackTrace()
#1 0x55fb19a74561 logging::LogMessage::~LogMessage()
#2 0x55fb17c0a019 ui::LatencyTracker::ComputeEndToEndLatencyHistograms()
#3 0x55fb17c098b5 ui::LatencyTracker::OnGpuSwapBuffersCompleted()
#4 0x55fb1ad074d5 viz::DisplayOutputSurface::OnGpuSwapBuffersCompleted()
#5 0x55fb188226f7 _ZN4base8internal7InvokerINS0_9BindStateIMN7content33GpuBrowse
rCompositorOutputSurfaceEFvRKNSt3__16vectorIN2ui11LatencyInfoENS5_9allocatorIS8_
EEEEN3gfx10SwapResultEPKN3gpu36GpuProcessHostedCALayerTreeParamsMacEEJNS_7WeakPt
rIS4_EEEEEFvSD_SF_SJ_EE3RunEPNS0_13BindStateBaseESD_OSF_OSJ
#6 0x55fb1a7a7335 gpu::InProcessCommandBuffer::DidSwapBuffersCompleteOnOriginThr
ead()
#7 0x55fb1a7a7eed _ZN4base8internal7InvokerINS0_9BindStateIMN3gpu22InProcessComm
andBufferEFvNS3_25SwapBuffersCompleteParamsEEJNS_7WeakPtrIS4_EENS0_13PassedWrapp
erIS5_EEEEEFvvEE7RunImplIRKS7_RKNSt3__15tupleIJS9_SB_EEEJLm0ELm1EEEEvOT_OT0_NSI_
16integer_sequenceImJXspT1_EEEE
#8 0x55fb19a5b30b base::debug::TaskAnnotator::RunTask()
#9 0x55fb19a7b20d base::MessageLoop::RunTask()
#10 0x55fb19a7b86f base::MessageLoop::DoWork()
#11 0x55fb19a7e149 base::MessagePumpLibevent::Run()
#12 0x55fb19a7acaa base::MessageLoop::Run()
#13 0x55fb19aa3f67 base::RunLoop::Run()
#14 0x55fb19ad00dc base::Thread::Run()
#15 0x55fb19ad0681 base::Thread::ThreadMain()
#16 0x55fb19ac8c3c base::(anonymous namespace)::ThreadFunc()
#17 0x7f468fd576ba start_thread
#18 0x7f468c00a3dd clone

Received signal 6
#0 0x55fb19a5abd7 base::debug::StackTrace::StackTrace()
#1 0x55fb19a5a6bf base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7f468fd61390 <unknown>
#3 0x7f468bf38428 gsignal
#4 0x7f468bf3a02a abort
#5 0x55fb19a594d2 base::debug::BreakDebugger()
#6 0x55fb19a74a2b logging::LogMessage::~LogMessage()
#7 0x55fb17c0a019 ui::LatencyTracker::ComputeEndToEndLatencyHistograms()
#8 0x55fb17c098b5 ui::LatencyTracker::OnGpuSwapBuffersCompleted()
#9 0x55fb1ad074d5 viz::DisplayOutputSurface::OnGpuSwapBuffersCompleted()
#10 0x55fb188226f7 _ZN4base8internal7InvokerINS0_9BindStateIMN7content33GpuBrows
erCompositorOutputSurfaceEFvRKNSt3__16vectorIN2ui11LatencyInfoENS5_9allocatorIS8
_EEEEN3gfx10SwapResultEPKN3gpu36GpuProcessHostedCALayerTreeParamsMacEEJNS_7WeakP
trIS4_EEEEEFvSD_SF_SJ_EE3RunEPNS0_13BindStateBaseESD_OSF_OSJ_
#11 0x55fb1a7a7335 gpu::InProcessCommandBuffer::DidSwapBuffersCompleteOnOriginTh
read()
#12 0x55fb1a7a7eed _ZN4base8internal7InvokerINS0_9BindStateIMN3gpu22InProcessCom
mandBufferEFvNS3_25SwapBuffersCompleteParamsEEJNS_7WeakPtrIS4_EENS0_13PassedWrap
perIS5_EEEEEFvvEE7RunImplIRKS7_RKNSt3__15tupleIJS9_SB_EEEJLm0ELm1EEEEvOT_OT0_NSI
_16integer_sequenceImJXspT1_EEEE
#13 0x55fb19a5b30b base::debug::TaskAnnotator::RunTask()
#14 0x55fb19a7b20d base::MessageLoop::RunTask()
#15 0x55fb19a7b86f base::MessageLoop::DoWork()
#16 0x55fb19a7e149 base::MessagePumpLibevent::Run()
#17 0x55fb19a7acaa base::MessageLoop::Run()
#18 0x55fb19aa3f67 base::RunLoop::Run()
#19 0x55fb19ad00dc base::Thread::Run()
#20 0x55fb19ad0681 base::Thread::ThreadMain()
#21 0x55fb19ac8c3c base::(anonymous namespace)::ThreadFunc()
#22 0x7f468fd576ba start_thread
#23 0x7f468c00a3dd clone
  r8: 00007f4675cd6400  r9: 00007f4675cd8700 r10: 0000000000000008 r11: 00000000
00000206
 r12: 00007f4675cd69b0 r13: 00000000000000dc r14: 00007f4675cd69a8 r15: 00007f46
75cd69a0
  di: 0000000000001d39  si: 0000000000001d5a  bp: 00007f4675cd6400  bx: 00007f46
75cd6400
  dx: 0000000000000006  ax: 0000000000000000  cx: 00007f468bf38428  sp: 00007f46
75cd6258
  ip: 00007f468bf38428 efl: 0000000000000206 cgf: 002b000000000033 erf: 00000000
00000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

#14 0x55fb19a7b20d base::MessageLoop::RunTask()
#15 0x55fb19a7b86f base::MessageLoop::DoWork()
#16 0x55fb19a7e149 base::MessagePumpLibevent::Run()
#17 0x55fb19a7acaa base::MessageLoop::Run()
#18 0x55fb19aa3f67 base::RunLoop::Run()
#19 0x55fb19ad00dc base::Thread::Run()
#20 0x55fb19ad0681 base::Thread::ThreadMain()
#21 0x55fb19ac8c3c base::(anonymous namespace)::ThreadFunc()
#22 0x7f468fd576ba start_thread
#23 0x7f468c00a3dd clone
  r8: 00007f4675cd6400  r9: 00007f4675cd8700 r10: 0000000000000008 r11: 00000000
00000206
 r12: 00007f4675cd69b0 r13: 00000000000000dc r14: 00007f4675cd69a8 r15: 00007f46
75cd69a0
  di: 0000000000001d39  si: 0000000000001d5a  bp: 00007f4675cd6400  bx: 00007f46
75cd6400
  dx: 0000000000000006  ax: 0000000000000000  cx: 00007f468bf38428  sp: 00007f46
75cd6258
  ip: 00007f468bf38428 efl: 0000000000000206 cgf: 002b000000000033 erf: 00000000
00000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

========================================================================

**Comment by tonikitoo** [comment]
Thank you for reporting. Same as issue #179 .

**Comment by Gyuyoung** [comment]
I verified this issue was fixed on latest version! Thx :)
