### ISSUE TITLE
[ozone/wayland] Crash when starting chromium/wayland with --start-fullscreen

### ISSUE THREAD

**Issue by tonikitoo** [Igalia/chromium#224]
ozone/x11 works fine.

**Comment by jaragunde** [comment]
Maybe related, I notice a strange behavior when using F11 to go fullscreen on a weston session. It will go through several states when you press it multiple times:
* complete fullscreen of the web contents
* fullscreen browser with visible chrome
* fullscreen content again, with hidden chrome
* fullscreen content with hidden chrome but visible weston top bar
* windowed mode

The following message appears several times on console:
[957:957:0906/131014.629226:ERROR:fullscreen_ozone.cc(12)] Not implemented reached in bool IsFullScreenMode(int64_t)

**Comment by tonikitoo** [comment]
I believe this is the way chromium toggles fullscreen. maybe on embedded HW these steps are processed slower, and then more visible to the user?

is that something also noticeable on chrome/mus on desktop?

**Comment by tonikitoo** [comment]
@jaragunde, could you please also validate this one after PR #237?

**Comment by tonikitoo** [comment]
I can not reproduce this crash, @jaragunde: please reopen if you see this happening again.
