### ISSUE TITLE
clicking on the window decoration does not activate the window

### ISSUE THREAD

**Issue by tonikitoo** [Igalia/chromium#229]
on the latests rebases (not the latest one), clicking on the (builtin) window decoration area does not activate properly activates it.

steps:
1- launch chrome/mus
2- create a second window (e.g. control+n)
2.1 click on the window decoration area to switch focus to the other window
OR
2.2 use alt-tab to switch focus to the other window.

Current outcome: host window manager brings the other window to front, but it does not gain focus (input isnt possible, and window decoration area is still painted grayed out). Only clicking on the web contents fully activates focus.

happens on both x11 and wayland ozone backends.

**Comment by msisov** [comment]
working on it

**Comment by tonikitoo** [comment]
Fixed by @msisov in PR #241.
