### ISSUE TITLE
Regression: menus are not hidden.

### ISSUE THREAD

**Issue by msisov** [Igalia/chromium#230]
Menu are not being hidden once a user clicks outside menu areas. This happens only in Wayland.

As regards X11, menus are not hidden once a user clicks outside browser window with menus opened.

**Comment by msisov** [comment]
https://github.com/Igalia/chromium/pull/231 is fixing wayland.

**Comment by tonikitoo** [comment]
good to close?

**Comment by msisov** [comment]
https://github.com/Igalia/chromium/pull/241 fixes X11's issue (a menu is not closed when user clicks outside the browser area, but just looses focus).

**Comment by msisov** [comment]
closing
