### ISSUE TITLE
Chrome fails to start because of failure when setting XKB keyboard mapping

### ISSUE THREAD

**Issue by ammen99** [Igalia/chromium#233]
Simply built with only ozone_wayland backend, NaCl disabled, without debug symbols, but it cannot run:
```
[5668:5708:0913/201545.225468:FATAL:wayland_keyboard.cc(66)] Check failed: success. Failed to set the XKB keyboard mapping.
#0 0x7f7b16fb2c0d base::debug::StackTrace::StackTrace()
#1 0x7f7b16fb0fdc base::debug::StackTrace::StackTrace()
#2 0x7f7b17041bba logging::LogMessage::~LogMessage()
#3 0x7f7b08e68f72 ui::WaylandKeyboard::Keymap()
#4 0x7f7afc7e0bde ffi_call_unix64
#5 0x7f7afc7e054f ffi_call
#6 0x7f7b08ef75f3 wl_closure_invoke
#7 0x7f7b08ef52a8 dispatch_event
#8 0x7f7b08ef461c dispatch_queue
#9 0x7f7b08ef4403 wl_display_dispatch_queue_pending
#10 0x7f7b08ef3f9e wl_display_dispatch_queue
#11 0x7f7b08ef4692 wl_display_dispatch
#12 0x7f7b08e5f8db ui::WaylandConnection::OnFileCanReadWithoutBlocking()
#13 0x7f7b17073ac1 base::MessagePumpLibevent::FileDescriptorWatcher::OnFileCanReadWithoutBlocking()
#14 0x7f7b17075289 base::MessagePumpLibevent::OnLibeventNotification()
#15 0x7f7b1733a4ee event_process_active
#16 0x7f7b17339b37 event_base_loop
#17 0x7f7b170753ec base::MessagePumpLibevent::Run()
#18 0x7f7b1706b014 base::MessageLoop::Run()
#19 0x7f7b17120d2d base::RunLoop::Run()
#20 0x7f7b171e9b04 base::Thread::Run()
#21 0x7f7b171ea724 base::Thread::ThreadMain()
#22 0x7f7b171ce781 base::(anonymous namespace)::ThreadFunc()
#23 0x7f7b1760936d start_thread
#24 0x7f7afeb96bbf __GI___clone

Received signal 6
#0 0x7f7b16fb2c0d base::debug::StackTrace::StackTrace()
#1 0x7f7b16fb0fdc base::debug::StackTrace::StackTrace()
#2 0x7f7b16fb25c5 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7f7b176143b0 <unknown>
#4 0x7f7afeabc69b __GI_raise
#5 0x7f7afeabe4a0 __GI_abort
#6 0x7f7b16fadfd6 base::debug::(anonymous namespace)::DebugBreak()
#7 0x7f7b16fadfb8 base::debug::BreakDebugger()
#8 0x7f7b17042876 logging::LogMessage::~LogMessage()
#9 0x7f7b08e68f72 ui::WaylandKeyboard::Keymap()
#10 0x7f7afc7e0bde ffi_call_unix64
#11 0x7f7afc7e054f ffi_call
#12 0x7f7b08ef75f3 wl_closure_invoke
#13 0x7f7b08ef52a8 dispatch_event
#14 0x7f7b08ef461c dispatch_queue
#15 0x7f7b08ef4403 wl_display_dispatch_queue_pending
#16 0x7f7b08ef3f9e wl_display_dispatch_queue
#17 0x7f7b08ef4692 wl_display_dispatch
#18 0x7f7b08e5f8db ui::WaylandConnection::OnFileCanReadWithoutBlocking()
#19 0x7f7b17073ac1 base::MessagePumpLibevent::FileDescriptorWatcher::OnFileCanReadWithoutBlocking()
#20 0x7f7b17075289 base::MessagePumpLibevent::OnLibeventNotification()
#21 0x7f7b1733a4ee event_process_active
#22 0x7f7b17339b37 event_base_loop
#23 0x7f7b170753ec base::MessagePumpLibevent::Run()
#24 0x7f7b1706b014 base::MessageLoop::Run()
#25 0x7f7b17120d2d base::RunLoop::Run()
#26 0x7f7b171e9b04 base::Thread::Run()
#27 0x7f7b171ea724 base::Thread::ThreadMain()
#28 0x7f7b171ce781 base::(anonymous namespace)::ThreadFunc()
#29 0x7f7b1760936d start_thread
#30 0x7f7afeb96bbf __GI___clone
  r8: 0000000000000000  r9: 00007f7ae001f050 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007f7ae0020070 r13: 0000000000000000 r14: fffffffffffffffc r15: 00007f7ae001ffd0
  di: 0000000000000002  si: 00007f7ae001f050  bp: 00007f7ae001f2a0  bx: 0000000000000028
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007f7afeabc69b  sp: 00007f7ae001f050
  ip: 00007f7afeabc69b efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

PS: Do you need such bugs reported? Or as you said in the other issue, the project is still not ready so now bug reports?

**Comment by tonikitoo** [comment]
Please report bugs :+1:. We will triage them all, and prioritize accordingly. All bugs / testers matter :)

'use_xkbcommon = true' on your GN args should fix this issue.

**Comment by ammen99** [comment]
Indeed, this solved the problem, so closing the issue. Now chromium works(albeit slower than usual, which is expected). Maybe this arg should be added to the build instructions?

**Comment by tonikitoo** [comment]
We should add the args to the build instructions, yes.

I will approve a PR request now that you had been brave enough to build it by hand. :)

README.md is the file to change IIRC.

**Comment by tonikitoo** [comment]
> Slower than usual

we are running on top of a fast moving target: MUS. Lots of performance are still being worked on by Google itself, and we foress benefiting from them "for free", performance-wise.

However, feel free to report any scenario that is way slower than it should be.

**Comment by ammen99** [comment]
Regarding the slowness: almost everything on every site is slower(there is noticeable lag), even new tab opening and loading pages that have no animations. So I don't think there is something specific to report. Anyway, it is a good job :+1: , I'm hopeful in the future you will be able to make it fast & fully functional :smile:

**Comment by tonikitoo** [comment]
odd, but it came to mind: do you have 'is_debug = false' in your GN flags?

for the record, 'is_debug' defaults to 'true', and indeed make things WAY slower.

**Comment by msisov** [comment]
You must explicitly set that this is not a debug build as long as gn assumes the debug build is the default one

**Comment by ammen99** [comment]
I'll try that now, however it'll take a very long time on my machine as I'll have to rebuild from scratch(and I have a 2C4T processor)

**Comment by ammen99** [comment]
Indeed, recompiling without debug makes chrome faster than through XWayland. However, is it normal that the GPU process should crash?

**Comment by ammen99** [comment]
Also, after using it for some time all web pages(excluding the new tab page) are blank(white), which is fixed  by deleting the profile directory. However, the issue gets back after a few minutes of usage

**Comment by msisov** [comment]
Can you provide us with a backtrace of gpu crash?

**Comment by ammen99** [comment]
The error was that it was unable to open the libosmesa.so because of missing libc++.so, I installed the corresponding package(I'm using Fedora 26), but now I get the following:
![screenshot-2017-09-14-15 44 58](https://user-images.githubusercontent.com/6287487/30430378-bd75c148-9963-11e7-8024-e6aa69293bea.png)

It is interesting that GL_RENDERER (not visible on the screenshot) is Mesa OffScreen v9.0.3, so maybe it doesn't detect my GPU at all

**Comment by msisov** [comment]
Try to run with --ignore-gpu-blacklist. The gpu might be blacklisted.

**Comment by ammen99** [comment]
This indeed makes almost all of these marked as working and resolves blank pages, however the version remains 9.0.3 whereas Xwayland chrome shows mesa 17(which is what is installed on my pc), so chrome still doesn't detect my GPU. Actually, why does the build compile libosmesa by itself, shouldn't this be provided by /lib64 ?

**Comment by ammen99** [comment]
What is the default target OS? Is it ChromeOS or the "host" - Linux?

**Comment by tonikitoo** [comment]
Default is linux. To build chromeos you need to specify "target_os = chromeos" on your GN args.

**Comment by tonikitoo** [comment]
about:gpu should show GPU rendering is enabled or not. In cause it is not, you get something like this:

![chromium_wayland_sw_rendering](https://user-images.githubusercontent.com/1540420/30432241-07e6f272-992f-11e7-94c8-e764ecdc4a73.png)

**Comment by ammen99** [comment]
Yes, it is with --ignore-gpu-blacklist. Otherwise I get blank pages a few minutes after resetting profile. But the drivers' version shouldn't be 9.0.3 in any case, this is ancient mesa, mine is 17.1.7

**Comment by ammen99** [comment]
In the previous comment I meant that GPU is used with --ignore-gpu-blacklist

**Comment by tonikitoo** [comment]
maybe chromium is using its own 'fork' of mesa: //third_party/mesa/README.chromium ?

**Comment by ammen99** [comment]
Seems this is the case, but why official builds don't use it? Is there any way to disable it?

**Comment by tonikitoo** [comment]
> This indeed makes almost all of these marked as working and resolves blank pages, however the version remains 9.0.3 whereas Xwayland chrome shows mesa 17(which is what is installed on my pc), so chrome still doesn't detect my GPU. Actually, why does the build compile libosmesa by itself, shouldn't this be provided by /lib64 ?

for completeness, we are not yet properly handling about:gpu, and I believe to have figured what the problem is.

In practice, GPU rendering *is* taking place with chrome/mus (i.e. GPU service run as a thread within the Browser process), but when about:gpu is loaded we try to launch the regular GPU process, which naturally fails in the case of ozone/wayland; in external window mode we do not support the regular GPU process.

This failure sends a "gpu process failed to launch" message to the browser process, and it causes a unreal status on about:gpu page (accusing all items as using SW rendering, which is not accurate).

The fact that an ancient OSMESA version is shown (10.7 IIRC) is also related to this.

I filed Issue #239  to track it properly.
