### ISSUE TITLE
Browser stops refreshing until input events are received

### ISSUE THREAD

**Issue by jaragunde** [Igalia/chromium#234]
Sometimes, web contents stop refreshing (e.g. if there is an animation, it stops working) until the browser receives some input event, for example, the mouse moves. It also affects to animations in the browser chrome: the animation of the loading spinner next to the tab name may stop too.

I've reproduced this problem on an embedded device (a hardware with a Snapdragon 600 ARM CPU), and always with Weston.

**Comment by jaragunde** [comment]
WebGL content doesn't seem to have this problem. CSS animations, [like this](https://webkit.org/blog-files/3d-transforms/poster-circle.html), have the problem, they stop working after a few seconds and resume when you move the mouse.

**Comment by tonikitoo** [comment]
jacobo: could you confirm this with latest ozone-wayland-dev?

**Comment by msisov** [comment]
we have not seen that issue for a long while. closing.
