### ISSUE TITLE
Enter/Backspace don't work upon startup

### ISSUE THREAD

**Issue by ammen99** [Igalia/chromium#240]
On the address bar, enter/backspace keys sometimes do not work. The easiest way to reproduce this is to close all tabs(thus closing chromium), then start it again from the command line and click the address bar. The problem is present every time I do this.

**Comment by msisov** [comment]
Hi. Can you check again with the latest changes fetched? Should be fixed by #241

**Comment by ammen99** [comment]
Tried to compile today, but ran into issues about libvpx. Will try purging all(including source) and downloading again.

 BTW: how to you make fetch download from this repo? I simply changed one of the prebuilt configs(changed only the source url), is there a better way or something else to be changed.

**Comment by msisov** [comment]
Fetch code from the upstream (fetch chromium), then do git remote add Igalia {source.git}. Then fetch Igalia, git checkout -b ozone-wayland-dev, git reset —hard Igalia/ozone-Wayland-dev, git pull Igalia ozone-Wayland-dev. And finally gclient sync

**Comment by msisov** [comment]
I meant git fetch Igalia

**Comment by ammen99** [comment]
@msisov  does this work with shallow clones? Doesn't it need to re-download everything when I run git fetch?

**Comment by msisov** [comment]
@ammen99, I haven't tried with shallow clones. You can skip git fetch part if you've already had a chromium copy. Pull the latest code from our repo and do gclient sync, which fetches all the third party dependancies.

**Comment by ammen99** [comment]
@msisov I managed to compile it, problem seems resolved. However, there is another keyboard related problem - there is no key repeating, however I believe this feature isn't implemented yet.

**Comment by msisov** [comment]
Right, it hasn't been implemented yet as long as we have more important items to be done now.
But patches are welcome!

**Comment by tonikitoo** [comment]
Fixed by @msisov in PR #241. Closing.
