### ISSUE TITLE
Hiding cursor doesn't work

### ISSUE THREAD

**Issue by ammen99** [Igalia/chromium#259]
To reproduce: open a youtube video, hover the mouse over it. The pointer should get hidden after a few seconds. However, under weston it becomes a black square and under gnome it doesn't hide at all(possibly gnome keeps the last "good" pointer surface). This happens in like 95% of the cases(in weston from time to time it works, but as I said, seldom). Is this a bug in chromium or in the compositors(because if I use xwayland's chrome it works)?

**Comment by msisov** [comment]
What weston version do you use?

**Comment by msisov** [comment]
It looks to be working with X11, but wayland is buggy.

**Comment by ammen99** [comment]
I tried with weston 2.00, 3.00 and latest git, Gnome 3.24.3

**Comment by msisov** [comment]
Opened a bug in the upstream. Closing in favor of https://bugs.chromium.org/p/chromium/issues/detail?id=895743
