### ISSUE TITLE
[ozone/wayland] Capture is not reset after dragging chrome window

### ISSUE THREAD

**Issue by tonikitoo** [Igalia/chromium#262]
create two chrome/mus windows, and load some scrollable content on each.
drag one the window away from the other
do some mouse wheels scrolling with in the focused window (it works!)
move mouse hover the unfocused window, and try to scroll with wheels (it scrolls the focused window).

This is because capture isnt being properly reset after dragging the window (via window decoration dragging).

**Comment by msisov** [comment]
fixed.
