### ISSUE TITLE
 dragging a tab outside does not create outer windows

### ISSUE THREAD

**Issue by tonikitoo** [Igalia/chromium#264]
we can drag tabs and change their position in the tabstrip, within the same chrome window, but not tag it outside the window to create a new one (like stock chrome).

**Comment by msisov** [comment]
I guess I'll take this next

**Comment by msisov** [comment]
PR #277

**Comment by msisov** [comment]
This is fixed, but requires some refactoring. As long as the initial goal was accomplished, closing this.
