### ISSUE TITLE
resize glitches

### ISSUE THREAD

**Issue by tonikitoo** [Igalia/chromium#265]
We discussed with @rjkroege during the WebEngines hackfest possible ways to avoid glitches when resizing an outter (ozone) chrome window.

General idea would be "make surface sync aware of external surface size changes".

This is just a reminder bug since bulk of work should be done upstream.

**Comment by rjkroege** [comment]
Scheme: when the external platform in external window mode resizes a `PlatformWindow` instance, it needs to allocate a new surface id for the window and communication that to `FrameGenerator` instance of the window tree. I think that this way we could get perfect Wayland resize handling.

**Comment by rjkroege** [comment]
@tonikitoo do you want to assign this to me?

**Comment by msisov** [comment]
@rjkroege please feel free to grab the bug! any help is welcomed!

**Comment by tonikitoo** [comment]
I believe the issue is not so severe on latest ozone-wayland-dev branch.

I will be pushing one extra guard, to avoid cycling back to the client a bounds the client itself set to the server.

**Comment by tonikitoo** [comment]
We are not doing any worse than stock chrome/x11. in fact, resizing on ozone/wayland goes really smooth in our ToT.

Closing.

**Comment by tonikitoo** [comment]
Never mind. It still occurs. Reopening.

**Comment by msisov** [comment]
doesn't occur with ozone/wayland and the desktop integration without mus.
