### ISSUE TITLE
switching from maximize to non-maximize by dragging the window does not update decorations properly

### ISSUE THREAD

**Issue by tonikitoo** [Igalia/chromium#270]
- put the chrome/mus in maximized state (e.g. by clicking on maximize button on the decoration area).
- drag the window from its decoration area so that the window gets unmaximized.
- window decoration buttons do not always update well, entering a broken state.

**Comment by tonikitoo** [comment]
assigning to msisov.

**Comment by msisov** [comment]
fixed by #273
