### ISSUE TITLE
[TEMP] Revive sandbox with some services once forking with unittests is fixed.

### ISSUE THREAD

**Issue by msisov** [Igalia/chromium#279]
At the moment, we fail to fork while running mus demo and some other unittests with test_ime_driver and mus_demo service involed.

For now, use sandbox type none to make the tests pass again.

Note, before https://chromium-review.googlesource.com/#/c/688484/, we've always forked without sandbox.

#278 is disabling sandboxes in certain services.

**Comment by msisov** [comment]
This happens only with debian based machines for some reason. No idea how to fix it. Maybe related to kernel configuration... though, I have user namespace sandboxing enabled.

**Comment by tonikitoo** [comment]
upstream bug by tsepez: https://bugs.chromium.org/p/chromium/issues/detail?id=788778

**Comment by msisov** [comment]
Cherry-picked and reverted #327
