### ISSUE TITLE
[TEMP] Start using chrome.map for chrome/mus/linux builds

### ISSUE THREAD

**Issue by tonikitoo** [Igalia/chromium#289]
Past https://crrev.com/c//739950 , we started to see one random crashes on ozone/wayland, upon window tear down (menus, main chrome windows, etc).

In other to keep our weekly rebasing policy, we opt'ed out the functionality in https://github.com/Igalia/chromium/commit/9afa37f5e775.

This bug indeed to track the proper solution, so that we do not diverge from stock chrome/x11.

**Comment by msisov** [comment]
Received signal 11 SEGV_MAPERR 000000000000
#0 0x55d091f4e7f3 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#1 0x7ffb721ac150 <unknown>
#2 0x7ffb553ec4dc <unknown>
#3 0x7ffb553eb7ac <unknown>
#4 0x7ffb553e956b <unknown>
#5 0x7ffb553e9a49 <unknown>
#6 0x7ffb5643a193 <unknown>
#7 0x7ffb5642caee <unknown>
#8 0x55d092c30488 gl::NativeViewGLSurfaceEGL::SwapBuffers()
#9 0x55d092c1e321 gl::GLSurfaceAdapter::SwapBuffers()
#10 0x55d09333c19c gpu::PassThroughImageTransportSurface::SwapBuffers()
#11 0x55d0932dbe09 gpu::gles2::GLES2DecoderImpl::DoSwapBuffers()
#12 0x55d09329c449 gpu::gles2::GLES2DecoderImpl::HandleSwapBuffers()
#13 0x55d0932bb358 gpu::gles2::GLES2DecoderImpl::DoCommandsImpl<>()
#14 0x55d09319b79f gpu::CommandBufferService::Flush()
#15 0x55d093187327 gpu::InProcessCommandBuffer::FlushOnGpuThread()

**Comment by msisov** [comment]
The issue is not reproducible in Debian builds, but in Ubuntu ones.

**Comment by msisov** [comment]
not applicable.
