### ISSUE TITLE
[ozone/wayland] restore-from-maximize isn't working well if browser starts maximized

### ISSUE THREAD

**Issue by tonikitoo** [Igalia/chromium#299]
- start chrome
- maximize it
- close it
- then launch again - it should start maximized
- press restore button

BUG: It disappears (0,0 0x0 bounds)

**Comment by msisov** [comment]
Can you please paste your environment here? I can't reproduce it with Gnome/Wayland, Weston and Xwayland.

**Comment by tonikitoo** [comment]
I am using gnone/wayland (ubuntu 17.10).

Steps I used

- launch chrome --mus normally.
- use SHIFT+ESC to launch "Task Manager"
- Maximize the "Task Manager" window (clicking on the maximize button)
- switch focus back to Chrome, and close the browser (the Task Manager window will also close by itself).
- relaunch chrome
- SHIFT+ESC to launch "Task Manager" again. It should start maximized, as per the previous session.
- unmaximize Task Manager by clicking on the restore button.

For me the window disappears.

**Comment by msisov** [comment]
Nope, it works OK for me.

**Comment by msisov** [comment]
not applicable any more.
