### ISSUE TITLE
[ozone/wayland] be able to run with use_xkbcommon = false

### ISSUE THREAD

**Issue by tonikitoo** [Igalia/chromium#303]
today it crashes at startup

[10613:10641:1124/133201.189503:FATAL:wayland_keyboard.cc(66)] Check failed: success. Failed to set the XKB keyboard mapping.
#0 0x7f68b0fb5403 base::debug::StackTrace::StackTrace()
#1 0x7f68b0fe798c logging::LogMessage::~LogMessage()
#2 0x7f68aba0685e ui::WaylandKeyboard::Keymap()
#3 0x7f68a362e038 ffi_call_unix64
#4 0x7f68a362da9a ffi_call
#5 0x7f68aba117e0 wl_closure_invoke
#6 0x7f68aba10107 dispatch_event
#7 0x7f68aba0fbda wl_display_dispatch_queue_pending
#8 0x7f68aba051f3 ui::WaylandConnection::OnFileCanReadWithoutBlocking()
#9 0x7f68b0ff71ef base::MessagePumpLibevent::OnLibeventNotification()

**Comment by msisov** [comment]
PR #321
