### ISSUE TITLE
v4l2_jpeg_decode_accelerator.cc path issue

### ISSUE THREAD

**Issue by mntmn** [Igalia/chromium#414]
I just did a fresh checkout and config and hit this problem:

>  % ninja -C out/Default chrome  
> ninja: Entering directory `out/Default'
> ninja: error: '../../media/gpu/v4l2_jpeg_decode_accelerator.cc', needed by 'obj/media/gpu/gpu/v4l2_jpeg_decode_accelerator.o', missing and no known rule to make it

Adding "v4l2/" directory prefixes in the 4 lines at https://github.com/Igalia/chromium/blob/ozone-wayland-dev/media/gpu/BUILD.gn#L240 fixes it.

**Comment by tonikitoo** [comment]
hi! what branch are you using, what are your GN args?

**Comment by mntmn** [comment]
Hi! Sorry for not providing all the specifics. I was under the wrong impression that this was a trivial thing. Actually the build has many little problems so it might be a config issue. The branch is ozone-wayland-dev at 7f25d821b27f652ed2bfa2a6168e2eed6df1b0ab. 

The gn args:

```
disable_libfuzzer=true
enable_av1_decoder=false
enable_background_contents=false
enable_desktop_in_product_help=false
enable_nacl=false
enable_native_notifications=false
enable_pdf=true
enable_plugins=true
enable_remoting=false
enable_reporting=false
enable_supervised_users=false
enable_service_discovery=false
enable_session_service=false
enable_wayland_server=true
enable_webrtc=false
proprietary_codecs=true
ffmpeg_branding="Chrome"
ozone_platform_wayland=true
ozone_platform_gbm=true
ozone_platform="wayland"
rtc_build_examples=false
use_dbus=false
use_jumbo_build=true
use_ozone=true
use_v4l2_codec=true
use_v4lplugin=true
use_linux_v4l2_only=true
is_debug=false
symbol_level=1
remove_webcore_debug_symbols=true
safe_browsing_mode=0
target_cpu="arm"
target_os="linux"
```

I disabled the following lines now and getting problems with some undefined identifiers related to Skia like SK_CRASH, so something is still off.

```
#use_v4l2_codec=true
#use_v4lplugin=true
#use_linux_v4l2_only=true
```

**Comment by mntmn** [comment]
Is it possible that `gclient sync` downloaded an incompatible/too new version of Skia? I'm getting errors like

```
In file included from gen/ui/gfx/color_space_jumbo_1.cc:5:
./../../ui/gfx/color_space.cc:503:14: error: 'SkMatrix44' is deprecated [-Werror,-Wdeprecated-declarations]
  SkMatrix44 custom_gamut;
             ^
../../third_party/skia/include/core/SkMatrix44.h:155:5: note: 'SkMatrix44' has been explicitly marked deprecated here
    SK_ATTR_DEPRECATED("use the constructors that take an enum")
    ^
../../third_party/skia/include/core/SkPostConfig.h:259:48: note: expanded from macro 'SK_ATTR_DEPRECATED'
#  define SK_ATTR_DEPRECATED(msg) SK_ATTRIBUTE(deprecated)
                                               ^
In file included from gen/ui/gfx/color_space_jumbo_1.cc:6:
./../../ui/gfx/icc_profile.cc:109:14: error: 'SkMatrix44' is deprecated [-Werror,-Wdeprecated-declarations]
  SkMatrix44 to_XYZD50_matrix;
             ^
../../third_party/skia/include/core/SkMatrix44.h:155:5: note: 'SkMatrix44' has been explicitly marked deprecated here
    SK_ATTR_DEPRECATED("use the constructors that take an enum")
    ^
../../third_party/skia/include/core/SkPostConfig.h:259:48: note: expanded from macro 'SK_ATTR_DEPRECATED'
#  define SK_ATTR_DEPRECATED(msg) SK_ATTRIBUTE(deprecated)
                                               ^
```

Or:

```
In file included from gen/cc/paint/paint_jumbo_1.cc:22:
./../../cc/paint/paint_op_buffer_serializer.cc:147:34: error: 'MakeFromIRect' is deprecated [-Werror,-Wdeprecated-declarations]
      ClipRectOp clip_op(SkRect::MakeFromIRect(device_column),
                                 ^
../../third_party/skia/include/core/SkRect.h:777:5: note: 'MakeFromIRect' has been explicitly marked deprecated here
    SK_ATTR_DEPRECATED("use Make()")
```

**Comment by mntmn** [comment]
Nervermind, the Skia problems were from including the wrong SkUserConfig.h. I originally tweaked the path to it in SkTypes.h because the compiler could not find SkUserConfig.h for some reason.

**Comment by tonikitoo** [comment]
Ok, thanks.

so just to make sure: problem happens when you have

> use_v4l2_codec=true
use_v4lplugin=true
use_linux_v4l2_only=true

?

Are you building for x86-64? Any toolchain (yocto, etc)?

**Comment by mntmn** [comment]
Yes, I have the problem with these options. I am cross-building for ARM (32 bit) on Debian Linux buster/sid. The build is still going. I've had to comment out some other odd bits in various files to make it continue at several failure points, I'll post a complete list when it's done.

No yocto, building with `ninja -C out/Default chrome`

**Comment by msisov** [comment]
closing old issue. reopen if anything.
