### ISSUE TITLE
Get real resolution of screen on Linux with mus

### ISSUE THREAD

**Issue by msisov** [Igalia/chromium#43]
As long as we don't wait until screen is detected, some default values are set. This leads to wrong placement of menu windows, eg, when once clicks 3-dot menu, it follows a root window, but as soon as root window is moved out of the default screen area (801x802 in our case, see - https://github.com/Igalia/chromium/commit/6b217e5ba298ec8320195fcdf5f842f965a6cdd6#diff-1b929b43ed9a373fec42ec2242e86a0aL63 ), menu windows are shown only on a certain area.

Commit 6b217e5 should be fixed.

**Comment by tonikitoo** [comment]
Both wayland and x11 backends have implementation. Support for multiple monitors is still missing, but I will file another bug for it.
