### ISSUE TITLE
 [Wayland/X11] Handle Tab dragging

### ISSUE THREAD

**Issue by jkim-julie** [Igalia/chromium#430]
Related to commit fc553553a5c2a323d0d591905775369e7851c7e6.

Current window_finder_ozone only works with mus.

[10276:10276:0511/124240.997375:FATAL:window_finder_ozone.cc(15)] Check failed: false. For Ozone builds, only mash launch is supported for now.
#0 0x7fe1ae300fbc base::debug::StackTrace::StackTrace()
#1 0x7fe1ae24337b logging::LogMessage::~LogMessage()
#2 0x560a6b7f390a WindowFinder::GetLocalProcessWindowAtPoint()
#3 0x560a6b7ee4f0 TabDragController::GetLocalProcessWindow()
#4 0x560a6b7ec899 TabDragController::GetTargetTabStripForPoint()
#5 0x560a6b7ec12d TabDragController::ContinueDragging()
#6 0x560a6b7ea646 TabDragController::Drag()
#7 0x560a6b7e4f12 TabStrip::ContinueDrag()
#8 0x560a6b7d99ad Tab::OnMouseDragged()
#9 0x7fe1a8eae96e views::View::ProcessMouseDragged()
#10 0x7fe1a8eae5cb views::View::OnMouseEvent()

**Comment by msisov** [comment]
From my last research, Wayland doesn't support window tab dragging. That is, when one drags a window, they can't know the exact location of a Wayland window (global coordinate are not available for users), which is used to unite a window with another window and make a new tab out of out.

However, users can drag tabs and created windows out of them.

For wayland, just implement ::RunMoveLoop and return early with Widget::MOVE_LOOP_SUCCESSFUL;

And Here is an example how DWTHx11 does it
https://cs.chromium.org/chromium/src/ui/views/widget/desktop_aura/desktop_window_tree_host_x11.cc?q=desktop_window_tree_host_x11.cc&sq=package:chromium&l=947 . 

So, in case of Wayland - return early, and in case of X11, do the normal procedure.

**Comment by ammen99** [comment]
@msisov I think it should be possible to implement this using wl_data_source, have you checked it? Wayland definitely supports drag and drop.

**Comment by msisov** [comment]
ammen99, hey. Indeed, I haven't considered that option. I'll check it later, thanks for the hint.

**Comment by msisov** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=896640
