### ISSUE TITLE
[ozone/wayland] supporting V4L2VDA

### ISSUE THREAD

**Issue by jkim-julie** [Igalia/chromium#437]
Related commits from previous branch.

-Add support for V4L2VDA on Linux(commit 8626a15aae1ed6dd509ecf2aeabf3a55999f909a)
-Add mmap via libv4l to generic_v4l2_device(commit c01b789bf54aac65c0597fd38615ff98b1fcd72e)
-fixup! avoid building not declared formats(commit 26605b5b20f5660c55b4cd87bbf9472551a9dcb8)

**Comment by msisov** [comment]
#438
