### ISSUE TITLE
Fix the derivation of void aura::TextInputClientImpl::ExtendSelectionAndDelete(size_t, size_t)

### ISSUE THREAD

**Issue by RyoKodama** [Igalia/chromium#466]
I tried building raspberry pi 3 image.
But I couldn't make it.
It can't derive. Because even though the arguments are different from the parent's one, but the derived class uses override specifier. The compile error message is below.
How can we fix it?

| In file included from ../../ui/aura/mus/input_method_mus.cc:13:0:
| ../../ui/aura/mus/text_input_client_impl.h:39:8: error: 'void aura::TextInputClientImpl::ExtendSelectionAndDelete(size_t, size_t)' marked 'override', but does not override
|    void ExtendSelectionAndDelete(size_t before, size_t after) override;
|         ^~~~~~~~~~~~~~~~~~~~~~~~
| In file included from /mnt/2502b19a-db74-4f7f-ac92-a0737fb929aa/kodama/FF-rc1/build_rpi3/tmp/work/armv7vehf-neon-vfpv4-agl-linux-gnueabi/chromium-ozone-wayland/67.0.3375.0.r543955.igalia.1-r0/recipe-sysroot/usr/include/c++/7.2.0/memory:80:0,
|                  from ../../mojo/public/cpp/bindings/strong_binding.h:8,
|                  from ../../ui/aura/mus/input_method_mus.h:10,
|                  from ../../ui/aura/mus/input_method_mus.cc:5:
| /mnt/2502b19a-db74-4f7f-ac92-a0737fb929aa/kodama/FF-rc1/build_rpi3/tmp/work/armv7vehf-neon-vfpv4-agl-linux-gnueabi/chromium-ozone-wayland/67.0.3375.0.r543955.igalia.1-r0/recipe-sysroot/usr/include/c++/7.2.0/bits/unique_ptr.h: In instantiation of 'typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = aura::TextInputClientImpl; _Args = {ui::TextInputClient*&, ui::internal::InputMethodDelegate*}; typename std::_MakeUniq<_Tp>::__single_object = std::unique_ptr<aura::TextInputClientImpl>]':
| ../../ui/aura/mus/input_method_mus.cc:178:64:   required from here
| /mnt/2502b19a-db74-4f7f-ac92-a0737fb929aa/kodama/FF-rc1/build_rpi3/tmp/work/armv7vehf-neon-vfpv4-agl-linux-gnueabi/chromium-ozone-wayland/67.0.3375.0.r543955.igalia.1-r0/recipe-sysroot/usr/include/c++/7.2.0/bits/unique_ptr.h:825:30: error: invalid new-expression of abstract class type 'aura::TextInputClientImpl'
|      { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
|                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| In file included from ../../ui/aura/mus/input_method_mus.cc:13:0:
| ../../ui/aura/mus/text_input_client_impl.h:21:7: note:   because the following virtual functions are pure within 'aura::TextInputClientImpl':
|  class TextInputClientImpl : public ui::mojom::TextInputClient {
|        ^~~~~~~~~~~~~~~~~~~
| In file included from ../../ui/aura/mus/input_method_mus.h:12:0,
|                  from ../../ui/aura/mus/input_method_mus.cc:5:
| gen/services/ui/public/interfaces/ime/ime.mojom.h:336:16: note: 	virtual void ui::mojom::TextInputClient::ExtendSelectionAndDelete(uint64_t, uint64_t)
|    virtual void ExtendSelectionAndDelete(uint64_t before, uint64_t after) = 0;
|                 ^~~~~~~~~~~~~~~~~~~~~~~~
| ninja: build stopped: subcommand failed.
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /mnt/2502b19a-db74-4f7f-ac92-a0737fb929aa/kodama/FF-rc1/build_rpi3/tmp/work/armv7vehf-neon-vfpv4-agl-linux-gnueabi/chromium-ozone-wayland/67.0.3375.0.r543955.igalia.1-r0/temp/log.do_compile.32583)
ERROR: Task (/mnt/2502b19a-db74-4f7f-ac92-a0737fb929aa/kodama/FF-rc1/meta-browser/recipes-browser/chromium/chromium-ozone-wayland_67.0.3375.0.r543955.igalia.1.bb:do_compile) failed with exit code '1'

**Comment by msisov** [comment]
The m71 recipe builds for the raspberry pi 3 without any issues. closing.
