### ISSUE TITLE
Segmentation fault on exit

### ISSUE THREAD

**Issue by mihailescu2m** [Igalia/chromium#468]
This might be specific to my platform (armhf + mali t628 old wayland drivers)

On exit, there's a segmentation fault. I don't have a debug build, and this is all I get with gdb:

`
Thread 1 "chrome" received signal SIGSEGV, Segmentation fault.
0xb5289832 in ?? () from /usr/lib/arm-linux-gnueabihf/libwayland-client.so.0
(gdb) bt
#0  0xb5289832 in  () at /usr/lib/arm-linux-gnueabihf/libwayland-client.so.0
#1  0xb5287066 in wl_proxy_destroy () at /usr/lib/arm-linux-gnueabihf/libwayland-client.so.0
#2  0xbeffedc0 in  ()
`

**Comment by msisov** [comment]
most probably fixed. closing.
