### ISSUE TITLE
mus_demo_unittests fail after April/17 rebase

### ISSUE THREAD

**Issue by tonikitoo** [Igalia/chromium#47]
The culprit is https://codereview.chromium.org/2804373002 ( Eliminate Connector::Connect(), Connection, etc.) - revert it and fixing a small conflict makes the test pass again.

Needs investigation.

**Comment by fred-wang** [comment]
@tonikitoo Per discussion with @msisov , I'm changing the title s/mus_tests_unitests/mus_ws_unitests

**Comment by fred-wang** [comment]
@tonikitoo What is mus_test_unittests? Do you mean mus_ws_unittests (It's already failing per https://github.com/Igalia/chromium/issues/11)

**Comment by fred-wang** [comment]
Test has been disabled in our bot for now: https://build-chromium.igalia.com/#/builders/1/builds/145

**Comment by tonikitoo** [comment]
fixed the description and title, @fred-wang

**Comment by tonikitoo** [comment]
I look at it a little bit today, and it fails even on vanilla chromeos/ozone build (ToT).

@fred-wang do you remember any bot that runs mus_demo_unittests?

**Comment by tonikitoo** [comment]
Mystery solved: mus_demo_unittests was actually not being build. After explicitly building the target 'services/ui/demo:mus_demo_unittests', mus_demo_unittests compiled and ran ok on linux and chromeos builds locally.

$ time ninja -C out/ozone/linux_os chrome mash:all ozone_unittests services/ui/demo/   services/ui/demo:mus_demo_unittests

$ ./out/ozone/linux_os//mus_demo_unittests --ozone-platform=x11IMPORTANT DEBUGGING NOTE: batches of tests are run inside their
own process. For debugging a test inside a debugger, use the
--gtest_filter=<your_test_name> flag along with
--single-process-tests.
Using sharding settings from environment. This is shard 0/1
Using 40 parallel jobs.
[1/2] MusDemoTest.CheckMusDemoDraws (229 ms)
[2/2] MusDemoTest.CheckMusDemoMultipleWindows (409 ms)
SUCCESS: all tests passed.
Tests took 0 seconds.

$  time ninja -C out/ozone/chrome_os/ chrome mash:all ozone_unittests services/ui/demo/ mash/browser  services/ui/demo:mus_demo_unittests
$ ./out/ozone/chrome_os/mus_demo_unittests --ozone-platform=x11IMPORTANT DEBUGGING NOTE: batches of tests are run inside their
own process. For debugging a test inside a debugger, use the
--gtest_filter=<your_test_name> flag along with
--single-process-tests.
Using sharding settings from environment. This is shard 0/1
Using 40 parallel jobs.
[1/1] MusDemoTest.CheckMusDemoDraws (481 ms)
SUCCESS: all tests passed.
Tests took 0 seconds.

**Comment by fred-wang** [comment]
@tonikitoo My comment about the bot was that mus_ws_unittests is now disabled (the issue title was wrong).

Mus Demo fails on the bot: https://build-chromium.igalia.com/#/builders/1/builds/200 and @msisov said it also fails locally for him.

Maybe a build target is missing on the Igalia bot?

**Comment by fred-wang** [comment]
@tonikitoo In Igalia's initial ticket I asked to build mus_demo_unittests.
