### ISSUE TITLE
[Not really an issue] Would it be possible to provide prebuilt binaries?

### ISSUE THREAD

**Issue by GorrillaRibs** [Igalia/chromium#503]
Sorry if this is too off topic for Issues, feel free to remove if it is. I'd love to test this, but have so far not been able to successfully build it (I'm sure it's something wrong on my end), and was wondering if it was feasible for you to provide a binary for testing. I've no idea how much work is involved in this (I'd assume just compiling with the flag is_debug=false?), but I figured it was worth asking even in the (very) likely event I'm wrong. Thanks!

**Comment by msisov** [comment]
that's possible, actually. Though, it depends on our availability. I'll try to figure out what we can do.

**Comment by hedgepigdaniel** [comment]
It's not a binary, but at least its automated - I made a AUR package for any Arch Linux users: https://aur.archlinux.org/packages/chromium-ozone-wayland-git/

Note that:
- compilation takes a long time - for me its about 4 hours.
- there's a good chance that something in it is broken outside of the confines of my dev machine or that it will break when new code is pushed or that my hacky patches to make it build cause problems
- to actually use wayland you need the `--ozone-platform=wayland` arg at runtime
- by default it makes a debug build which is about 4GB but provides nice stack traces on errors

Feedback welcome.

**Comment by nickdiego** [comment]
> It's not a binary, but at least its automated - I made a AUR package for any Arch Linux users: https://aur.archlinux.org/packages/chromium-ozone-wayland-git/

Hey @hedgepigdaniel, that's great!
Thanks for contributing. I use Arch and will try it by myself :)

BTW, just remembered [this previous effort to create an AUR](https://github.com/Igalia/chromium/issues/311). It's out of date but maybe you can get some insights from it.

**Comment by msisov** [comment]
@hedgepigdaniel hi! would it be possible to change the repo to https://github.com/Igalia/chromium/tree/ozone-wayland-stable/72.0.3626.81 instead?

I'm taking latest stable releases and backport wayland patches to there. By using these kind of branches, we can make sure the browser is more stable.

**Comment by hedgepigdaniel** [comment]
Sure, I'll give that a go. Might make more sense to make it a different package, e.g. `chromium-ozone`.

Perhaps also I'll try downloading the source from chromium.googlesource.com and then patching it instead of using gclient etc.

**Comment by hedgepigdaniel** [comment]
Here it is: https://aur.archlinux.org/packages/chromium-ozone/

Other than the patches in that branch, I also needed https://github.com/chromium/chromium/commit/6c0254a78043e32441dbc2e6d4893590dd0d1953 for it to build successfully, and https://github.com/Igalia/chromium/commit/cdb2e638d4488936c80a2c1b506eecf95ffbee02 for it to build with VAAPI enabled.

Strangely, I made a non-debug build but it still comes out as 3.7GB of binaries... so I'm a little confused what happens to make the official packages.

**Comment by skewty** [comment]
Any chance at using CI to make RPM, DEB, .tgz files (etc)?
