### ISSUE TITLE
Crash on startup without `--in-process-gpu`

### ISSUE THREAD

**Issue by ammen99** [Igalia/chromium#507]
Try starting chromium without `--in-process-gpu`, getting just this. Latest commit in this repo.
Backtrace:
https://pastebin.com/UVzJ6vyu

**Comment by msisov** [comment]
2 possible issues:
1) wrong usage of minigbm and related gn args.
2) missing render node support.

what are your gn args?

check that render node exists

```
$ ls -la /dev/dri/renderD12*
crw-rw----+ 1 root video 226, 128 marra 30 21:17 /dev/dri/renderD128
crw-rw----+ 1 root video 226, 129 marra 30 21:17 /dev/dri/renderD129
```

**Comment by ammen99** [comment]
Hi, I have the render nodes (just renderD128 on my system, but that is because I have a single GPU).

My gn args: `use_ozone=true use_xkbcommon=true enable_nacl=false is_debug=false symbol_level=0 use_sysroot=false remove_webcore_debug_symbols=true use_jumbo_build=true`

The only thing that seems like it might cause problems is the `enable_nacl`, but I think I've seen people build chromium without nacl and it worked fine.

**Comment by msisov** [comment]
Ok. you're using third_party/minigbm without specifying gpu driver.

Switch off the minigbm and use a system one -
use_system_minigbm=true

**Comment by ammen99** [comment]
@msisov Thank you very much for your help. It works now.
