### ISSUE TITLE
Build fails when vaapi sources are included

### ISSUE THREAD

**Issue by qnixsynapse** [Igalia/chromium#511]
I'm using the  official patch and when compiling with ozone flags fails at the final linking:
```
../../media/gpu/vaapi/vaapi_picture_factory.cc:74: error: undefined reference to 'media::VaapiPictureNativePixmapOzone::VaapiPictureNativePixmapOzone(scoped_refptr<media::VaapiWrapper> const&, base::RepeatingCallback<bool ()> const&, base::RepeatingCallback<bool (unsigned int, unsigned int, scoped_refptr<gl::GLImage> const&, bool)> const&, int, gfx::Size const&, unsigned int, unsigned int, unsigned int)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```
Edit : Tried also without the patch but used "use_vaapi=true" resulted in the same error.
I tried hard to find out the root cause and failed. If anyone can help me out with this.
Thanks in advance.

**Comment by msisov** [comment]
sorry, we haven't used vaapi with ozone. Can you share a link to the patch you used?

**Comment by qnixsynapse** [comment]
@msisov I am using this https://github.com/chromium/chromium/commit/31225b9c5f3f685d65f742dc129241c30c32157c

with use_vaapi=true flag.

**Comment by msisov** [comment]
We haven't tried with vaapi, but let me try

**Comment by qnixsynapse** [comment]
@msisov  Thank you very much :+1: :)

**Comment by msisov** [comment]
I added a patch to be able to build with it, but haven't tested the functionality. feel free to ping if anything
