### ISSUE TITLE
Needs libffi.6?

### ISSUE THREAD

**Issue by Alex-Aralis** [Igalia/chromium#515]
I'm sitting out here in gentoo land and only have libffi.7 but when i try to build chromium for wayland it screams for libffi.6.  Looking at the version compiled by the system, it's using the libffi.7 and i'm wondering what's up?  Is it one of the gentoo specific patches to chromium that makes it use libffi.7 instead of 6?  

Here's the ebuild for vanilla chromium in case it helps.
https://gitweb.gentoo.org/repo/gentoo.git/tree/www-client/chromium/chromium-71.0.3578.80.ebuild

**Comment by msisov** [comment]
Wayland relies on libffi, but there is no specific version needed - 

```
third_party/wayland/BUILD.gn:43:      "//build/config/linux/libffi",
third_party/wayland/BUILD.gn:80:      "//build/config/linux/libffi",
third_party/wayland/BUILD.gn:101:      "//build/config/linux/libffi",
third_party/wayland/BUILD.gn:129:      "//build/config/linux/libffi",

build/config/linux/libffi/BUILD.gn:7:pkg_config("libffi") {
build/config/linux/libffi/BUILD.gn:8:  packages = [ "libffi" ]

```

But there are instrumented_libraries, which rely on libffi6

```
third_party/instrumented_libraries/BUILD.gn:116:      ":libffi6",
third_party/instrumented_libraries/BUILD.gn:474:  instrumented_library("libffi6") {
third_party/instrumented_libraries/scripts/install-build-deps.sh:32:libffi6 \
third_party/instrumented_libraries/scripts/install-build-deps.sh:93:  # zlib1g and libffi remove gcc-4.8 in favor of gcc-multilib,
```

**Comment by msisov** [comment]
Feel free to reopen.
