### ISSUE TITLE
Per-monitor HiDPI scaling does not work correctly

### ISSUE THREAD

**Issue by hedgepigdaniel** [Igalia/chromium#527]
When dragging windows between screens of high and low pixel densities, chromium does not adjust its window scale correctly. The windows are sometimes the wrong scale, and on a HiDPI screen, the UI is always blurry.

For scaling, there seem to be two separate binary states.
- One which switches correctly as it passes the boundary between screens. The scale doubles when it passes onto a HiDPI screen, and vice versa. This is what I expect.
- There is also a additional doubling of the UI size which sometimes occurs. It can be triggered by maximising the window on a HiDPI screen, and reversed by unmaximising it on a standard DPI screen. In this state, the window scale is too large on all screens. When not in this state, the window is the correct scale on all screens. This persists when dragging a window between screens.

In all cases on a HiDPI screen, the window is blurry. It looks like the resolution of the window is half that of the screen.

**Comment by msisov** [comment]
Thanks for reporting. Will it be possible to report to crbug.com instead?

**Comment by hedgepigdaniel** [comment]
Sure - is that the process for all bugs or are there some things that should go here?

**Comment by msisov** [comment]
Basically, everything must go there. We are in process of moving everything to upstream.

Even now, we merge patches to upstream first and rebase this branch each Monday to fetch all the changes we had there.

This branch is going to be used to keep v4l2 patches and ozone/x11 patches for some time.

plus our internal buildbot will be using it for some uncertain amount of time (before upstream has a dedicated wayland bot)

**Comment by hedgepigdaniel** [comment]
Great OK, So bugs related to Wayland support go upstream, but bugs with X11 in ozone builds or v4l2 go here.

Btw, love your work! I'm finally writing this from chromium running on wayland... its not finished, but it feels good :smiley:

**Comment by msisov** [comment]
Thank you!

**Comment by msisov** [comment]
and one more thing - whenever a bug is reported, please assign it it msisov@igalia.com or nickdiego@igalia.com or adunaev@igalia.com or rjkroege@chromium.org

**Comment by hedgepigdaniel** [comment]
I don't think I have the ability to assign tickets, but I've created this one for a different issue: https://bugs.chromium.org/p/chromium/issues/detail?id=929632

**Comment by hedgepigdaniel** [comment]
And this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=929871

**Comment by msisov** [comment]
Thanks.
