### ISSUE TITLE
Excessive UI scaling on HiDPI displays

### ISSUE THREAD

**Issue by nostdm** [Igalia/chromium#532]
Build: https://aur.archlinux.org/packages/chromium-ozone/
Version: 72.0.3626.81
Compositor: Sway

When starting chromium it seems to scale the UI according to the display resolution (2x in my case), but since Sway is already set to use scale of 2x, chromium starts with a combined scale of 4x.

Running the binary with --ozone-platform=wayland --in-process-gpu --high-dpi-support=0 --force-device-scale-factor=1 doesn't fix the excessive scaling.

Would this be a problem with Sway or is there a different way to force chromium to not scale the UI?

**Comment by msisov** [comment]
HDPI patch is under review now. It will be merged soon.

**Comment by msisov** [comment]
The patch is going to be included in the 72.0.3626.119 update.
