### ISSUE TITLE
Ozone/Wayland with stable 72.0.3626.119 has been pushed.

### ISSUE THREAD

**Issue by msisov** [Igalia/chromium#533]
I would like to notify everybody (I guess that's the only way how to notify users, who watch this repo) that an Ozone/Wayland with stable 72.0.3626.119 has just been pushed. It involves more backported patches from the ToT including fixed software rendering, improved compatibility with different Wayland compositors,
non-us keyboard layout support and etc.

Link the branch is here - https://github.com/Igalia/chromium/tree/ozone-wayland-stable/72.0.3626.119

**Comment by msisov** [comment]
Please, make sure you use at least the following args:

use_system_libdrm=true
use_system_minigbm=true
use_ozone=true
ozone_platform_wayland=true
use_xkbcommon=true

**Comment by hedgepigdaniel** [comment]
EDIT: I take it back, the problem was with git, patches, and caching.

**Comment by msisov** [comment]
Fooh. I was scared :)

**Comment by ammen99** [comment]
I still wish we had some binaries, compiling chromium is a difficult task for weaker computers. But anyway great work!
