### ISSUE TITLE
Ozone/Wayland with stable 73.0.3683.75 has been pushed.

### ISSUE THREAD

**Issue by msisov** [Igalia/chromium#534]
I would like to notify everybody that an Ozone/Wayland with stable  73.0.3683.75 has just been pushed.

Link to the branch is here - https://github.com/Igalia/chromium/tree/ozone-wayland-stable/73.0.3683.75

Make sure you compile at least with following args
use_ozone = true
ozone_platform_wayland = true
use_system_minigbm = true
use_system_libdrm = true
use_xkbcommon = true

**Comment by ammen99** [comment]
`use_system_gm` -> `use_system_libgbm` ?
