### ISSUE TITLE
upstream builds supporting wayland?

### ISSUE THREAD

**Issue by edrex** [Igalia/chromium#540]
is there any upstream tracking issue/discussion/work for enabling wayland support in the Canary channel? I'd like to start testing but doing my own builds is a big hurdle. (swaywm user)

**Comment by edrex** [comment]
previous discussion: #232

**Comment by edrex** [comment]
I found https://ci.chromium.org/p/chromium/builders/ci/linux-ozone-rel but I have no idea what I'm doing and I assume this is just for running tests and doesn't actually publish an artifact?

**Comment by msisov** [comment]
Hi @edrex. The work is fully upstream now and we no longer rebase or submit patches to this downstream repo. Please refer to https://cs.chromium.org/chromium/src/docs/ozone_overview.md?l=250 (though, the docs need to be updated).

The meta-bug in upstream is located at 
https://bugs.chromium.org/p/chromium/issues/detail?id=578890

If you are interested in testing, please refer to https://chromium.googlesource.com/chromium/src/+/master/docs/linux_build_instructions.md how-to to checkout the code.

PS we are not able to have official alpha/beta/stable releases yet as long as X11 has to be migrated to Ozone first. The idea is to have one binary, which would be able to run on Wayland or X11 as a native application.
