### ISSUE TITLE
allow window dragging when interacting with chromium's builtin window decoration (caption area)

### ISSUE THREAD

**Issue by tonikitoo** [Igalia/chromium#64]
in regular x11/linux, when using chromium's builtin window decoration, it is possible to drag the outer window around by drag and move its "caption" area (about the tapstrip).

we should allow the same on linux/ozone.

**Comment by msisov** [comment]
Wayland: solved by https://github.com/Igalia/chromium/pull/117
X11: pending

**Comment by msisov** [comment]
X11: https://github.com/Igalia/chromium/pull/135

**Comment by tonikitoo** [comment]
Fixed?

**Comment by msisov** [comment]
Fixed. Reopen if new issues are found.
