### ISSUE TITLE
Disallow to make submenu windows by hovering into a main menu in wayland

### ISSUE THREAD

**Issue by msisov** [Igalia/chromium#65]
The way to create a menu window, which would be properly placed in regards of a main window, is to use an xdg_popup, but Wayland creates xdg_popups by taking a serial number of a certain event as a parameter. Those event are touch and press events. Leave/Enter events' serial won't work there.

Instead, allow chrome to create submenu only after clicking on menu.

https://people.freedesktop.org/~whot/wayland-doxygen/wayland-protocols/Server/structxdg__shell__interface.html#aa5ab7b36ab8e2a5523ee1976d2d7bf56

**Comment by tonikitoo** [comment]
Good to close?

**Comment by msisov** [comment]
Yep, closing. Hovering works now.
