### ISSUE TITLE
Destroy ui::ws::Display once menu window is hidden

### ISSUE THREAD

**Issue by msisov** [Igalia/chromium#66]
As of now everything is destroyed except a ws::Display. When 3dot menu or right click menu is about to be hidden, almost all of the objects are destroyed, and when it is about to be shown again, new ws::Display is created. We grow in memory and don't release this resources.

**Comment by tonikitoo** [comment]
more info from issue #112:

1) open one browser window.
then open another (control+n or menu)
close a window pressing "x".

ui::ws::Display::~Display is never called.

2) we are currently only destroying ui::ws::Display instances upon exit:

#0 0x556221d6b817 base::debug::StackTrace::StackTrace()
#1 0x556224db43c0 ui::ws::Display::~Display()
#2 0x556224db46a9 ui::ws::Display::~Display()
#3 0x556224d93d51 ui::ws::DisplayManager::DestroyDisplay()
#4 0x556224d93680 ui::ws::DisplayManager::DestroyAllDisplays()
#5 0x556224da0405 ui::ws::WindowServer::~WindowServer()
#6 0x556224da0839 ui::ws::WindowServer::~WindowServer()
#7 0x55622193ea18 ui::Service::~Service()
#8 0x55622193eba9 ui::Service::~Service()
(..)

**Comment by msisov** [comment]
Fixed by https://github.com/Igalia/chromium/pull/169
