### ISSUE TITLE
Fix minimize/maximize events from Chrome in mus.

### ISSUE THREAD

**Issue by msisov** [Igalia/chromium#75]
That is, as of now they are no-op buttons.

**Comment by msisov** [comment]
X11 is fixed. What's left is wayland support.

**Comment by msisov** [comment]
Fixed by https://github.com/Igalia/chromium/pull/104 https://github.com/Igalia/chromium/pull/97  https://github.com/Igalia/chromium/pull/94 https://github.com/Igalia/chromium/pull/83

**Comment by msisov** [comment]
I'll keep it open as long as there is one minor thing missing in Wayland: send the window state back to aura through delegate.

**Comment by msisov** [comment]
Another two fixes: https://github.com/Igalia/chromium/pull/130 and https://github.com/Igalia/chromium/pull/127

**Comment by tonikitoo** [comment]
msisov: Good to close?

**Comment by msisov** [comment]
Fixed. Reopen if new issues are found.
