### ISSUE TITLE
chromium mus does not accept URL argument

### ISSUE THREAD

**Issue by fred-wang** [Igalia/chromium#99]
Testing this morning with Maksim,

      chromium --mus http://www.igalia.com

opens the default Google page instead of Igalia's website. In particular, this prevents from running https://github.com/Igalia/ces-demos-2017/blob/master/bin/sw-vs-hw-chrome.sh

**Comment by tonikitoo** [comment]
assigning to maksim.

**Comment by msisov** [comment]
fixed. PR: https://github.com/Igalia/chromium/pull/103

**Comment by msisov** [comment]
https://chromium-review.googlesource.com/c/604797
